import { ABILITY_LABELS, STAGES } from "./content.mjs?v=23";
import { LIFE_CARDS, LEISURE_CARDS, TRAINING_CARDS, CONTACTS, SIDE_QUESTS } from "./life-content.mjs?v=23";
import { NIGHT_CARDS } from "./night-content.mjs?v=23";
import { CHAPTER_EVENTS } from "./chapter-content.mjs?v=23";
import { FACTIONS, TERRITORIES, factionById, territoryById } from "./faction-content.mjs?v=23";
import { TEAM_MEMBERS, TEAM_LIMIT } from "./team-content.mjs?v=24";
import { DIFEI_EVENTS, characterEventById } from "./character-content.mjs?v=24";
import { ASSET_CATEGORY_LABELS } from "./market-content.mjs?v=23";
import { GameError, newGame, generateCards, getEvent, selectCard, resolveChoice, resolveActivity, resolveNightOption, acceptSideQuest, declineSideQuests, resolveSideQuestChoice, abandonSideQuest, upgradeAsset, startFactionFight, startTerritoryFight, fortifyTerritory, recruitCrew, recruitTeamMember, toggleTeamMember, teamRecruitCost, teamTrainingCost, characterLevelChance, pendingCharacterEvent, startCharacterEvent, resolveCharacterEventChoice, activeTeamMembers, teamBonuses, assetBonuses, contactBonuses, factionFightCost, territoryFortifyCost, controlledTerritories, territoryIncome, crewPower, battleAction, continueStage, continueChapterTransition, continueFreePlay, validateSave, endingText, modifyValue, saveCardDefinition, deleteCustomCard } from "./engine.mjs?v=24";

const SAVE_KEY="crime-five-roads-save-v2"; const app=document.querySelector("#app"); let state=null; let error="";let modifierOpen=false;
const esc=value=>String(value??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
const HERO_ART={desktop:"assets/images/hero-harbor-desktop.webp",mobile:"assets/images/hero-harbor-mobile.webp",alt:"雨夜海港高架橋下的公共電話亮著綠光，遠處可見港口與燒毀的運鈔車"};
const EVENT_ART={
  signal:{desktop:"assets/images/event-signal-desktop.webp",mobile:"assets/images/event-signal-mobile.webp",alt:"雨中的海港公共電話正在響，玻璃上有一道難以辨認的人影"},
  runner:{desktop:"assets/images/event-runner-desktop.webp",mobile:"assets/images/event-runner-mobile.webp",alt:"受傷的年輕車手倒在雨夜港區住處門前，手中緊握一把保險箱鑰匙"},
  ch1_burner:{desktop:"assets/images/event-ch1-burner-desktop.webp",mobile:"assets/images/event-ch1-burner-mobile.webp",alt:"港區修車廠的桌上攤著金庫藍圖，黑膠帶下露出第三個簽名"},
  checkpoint:{desktop:"assets/images/event-checkpoint-desktop.webp",mobile:"assets/images/event-checkpoint-mobile.webp",alt:"雨夜跨海大橋入口被黑色車輛與路障封鎖，只留下一條狹窄通道"},
  ambush:{desktop:"assets/images/event-ambush-desktop.webp",mobile:"assets/images/event-ambush-mobile.webp",alt:"兩名男子躲在高架橋下的水泥護欄後，黑色休旅車封住雨夜道路"},
  vault:{desktop:"assets/images/event-vault-desktop.webp",mobile:"assets/images/event-vault-mobile.webp",alt:"市府地下金庫大門敞開，贓款、錄音帶、硬碟與金庫藍圖散落在潮濕地面"},
  ch3_escape:{desktop:"assets/images/event-ch3-escape-desktop.webp",mobile:"assets/images/event-ch3-escape-mobile.webp",alt:"若琳、小凱與老六在雨夜修車廠看見自己的警方監視畫面，得知三人已被全城通緝"},
  ch3_container:{desktop:"assets/images/event-ch3-container-desktop.webp",mobile:"assets/images/event-ch3-container-mobile.webp",alt:"若琳在雨夜貨櫃船上拆接離線伺服器，小凱守在貨櫃門口警戒"},
  ch3_broadcast:{desktop:"assets/images/event-ch3-broadcast-desktop.webp",mobile:"assets/images/event-ch3-broadcast-mobile.webp",alt:"若琳與老六操作緊急通訊設備，窗外港城在斷訊後只剩稀疏警示燈"},
  ch4_election:{desktop:"assets/images/event-ch4-election-desktop.webp",mobile:"assets/images/event-ch4-election-mobile.webp",alt:"建商代表與幫派中間人在未完工高樓的長桌兩側秘密競標市長選舉"},
  ch4_betrayal:{desktop:"assets/images/event-ch4-betrayal-desktop.webp",mobile:"assets/images/event-ch4-betrayal-mobile.webp",alt:"空蕩修車廠的工作檯留下車鑰匙，監視器顯示若琳自願上了阿哲的車"},
  ch4_truth:{desktop:"assets/images/event-ch4-truth-desktop.webp",mobile:"assets/images/event-ch4-truth-mobile.webp",alt:"阿哲在市政控制室展示主控鑰匙，身後的城市基礎設施路線逐一亮起"},
  ch5_siege:{desktop:"assets/images/event-ch5-siege-desktop.webp",mobile:"assets/images/event-ch5-siege-mobile.webp",alt:"若琳、小凱與老六在黎明前手動打開海港封鎖線，協助居民與證人撤離"},
  ch5_tower:{desktop:"assets/images/event-ch5-tower-desktop.webp",mobile:"assets/images/event-ch5-tower-mobile.webp",alt:"若琳與小凱進入新塔樓中沒有正式編號的狹長機械層，遠端可見密封控制庫"},
  ch5_finale:{desktop:"assets/images/event-ch5-finale-desktop.webp",mobile:"assets/images/event-ch5-finale-mobile.webp",alt:"阿哲在跨海資料中心啟動主控鑰匙，警察、幫派、企業、居民與同伴同時逼近"},
  difei_spar_event:{desktop:"assets/images/difei-spar-desktop.webp",mobile:"assets/images/difei-spar-mobile.webp",alt:"狄菲在安全屋訓練角落收住最後一拳"},
  difei_media_event:{desktop:"assets/images/difei-media-desktop.webp",mobile:"assets/images/difei-media-mobile.webp",alt:"狄菲在雨中的舊比賽場館外被媒體包圍"},
  difei_interview_event:{desktop:"assets/images/difei-interview-desktop.webp",mobile:"assets/images/difei-interview-mobile.webp",alt:"狄菲站在空蕩拳台的聚光燈下接受公開訪問"}
};
const CHARACTER_ART=[
  {id:"azhe",name:"阿哲",role:"失蹤搭檔",src:"assets/images/characters/azhe.webp",alt:"身穿深色雨衣、臉側留有舊疤的阿哲"},
  {id:"mira",name:"若琳",role:"修車廠經營者",src:"assets/images/characters/mira.webp",alt:"穿著深色工作服、手上沾有油污的若琳"},
  {id:"kael",name:"小凱",role:"年輕車手",src:"assets/images/characters/kael.webp",alt:"穿著黑色皮外套、被雨淋濕的小凱"},
  {id:"zero",name:"老六",role:"酒保與情報販子",src:"assets/images/characters/zero.webp",alt:"戴著細框眼鏡、站在港區酒吧裡的老六"},
  {id:"difei",name:"狄菲",role:"助理與護衛",src:"assets/images/characters/difei.webp",alt:"留著黑色及腰長髮、穿白色運動內衣與黑色運動短褲的狄菲"},
  {id:"chenglan",name:"程嵐",role:"天才警務情報員",src:"assets/images/characters/chenglan.webp",alt:"綁低馬尾、穿深色連帽外套與機能短褲的程嵐"}
];
function responsiveArt(art,className,loading="lazy"){if(!art)return "";return `<picture class="${className}"><source media="(max-width: 760px)" srcset="${art.mobile}"><img src="${art.desktop}" alt="${esc(art.alt)}" loading="${loading}" decoding="async"${loading==="eager"?' fetchpriority="high"':""}></picture>`;}
function persist(){ try{localStorage.setItem(SAVE_KEY,JSON.stringify(state));}catch(e){error="無法寫入本機存檔，遊戲仍可繼續。";} }
function commit(fn){ try{state=fn(); error=""; persist(); render();}catch(e){error=e instanceof GameError?e.message:"發生未預期錯誤，狀態未被修改。"; render(); console.error(e);} }
function meter(label,value,max=100){return `<div class="stat">${label}<b>${value}</b><div class="meter"><span style="width:${Math.max(0,Math.min(100,value/max*100))}%"></span></div></div>`;}
function compactStat(label,value,max){return `<span><small>${label}</small><b>${value}/${max}</b></span>`;}
function stageLabel(){if(state.stage===0&&state.deckType==="life")return "上午・生活";if(state.stage===0&&state.deckType==="morning")return "上午・自由選擇";return STAGES[state.stage]||"終局";}
function header(){return `<header><div><h1>罪城：五路亡命</h1><div class="muted">現代／海港市／純文字犯罪劇</div></div><div class="header-actions"><span class="muted">第 ${state.chapter||1} 章／第 ${state.day} 日　${stageLabel()}</span><button class="secondary" data-modifier>${modifierOpen?"返回遊戲":"修改器"}</button></div></header>
  <div class="core-stats">${compactStat("健康",state.player.health,100)}${compactStat("疲勞",state.player.fatigue,100)}${compactStat("精神",state.player.stress,100)}${compactStat("現金",state.player.resource,999)}${compactStat("狄菲",state.relations.difei,100)}${compactStat("街坊",state.world.people,100)}</div>
  <div class="abilities"><strong>八大能力</strong><div class="ability-grid">${Object.entries(ABILITY_LABELS).map(([key,label])=>`<div><span>${label}</span><b>${state.player.abilities[key]}</b></div>`).join("")}</div></div>
  ${overview()}`;}
function overview(){const owned=controlledTerritories(state),assetCount=Object.values(state.assets||{}).flat().length,quest=state.activeSideQuest,pending=state.pendingRetaliation?territoryById(state.pendingRetaliation.territoryId):null;return `<details class="overview ${pending?"under-attack":""}"><summary><b>其他資訊</b><span>地盤 ${owned.length}/${TERRITORIES.length}</span><span>支線 ${quest?"1":"0"}</span><span>資產 ${assetCount}</span>${pending?`<strong>${esc(pending.name)}遭到反攻</strong>`:""}</summary><div class="overview-grid">${territoryLine()}${buffLine()}${sideQuestLine()}<section class="overview-card"><h3>持有資產（${assetCount}）</h3><div class="asset-list">${assetList()}</div></section>${castLine()}</div></details>`;}
function castLine(){const visible=CHARACTER_ART.filter(character=>character.id==="azhe"||state.knownContacts?.includes(character.id));return `<section class="overview-card cast-card"><h3>人物檔案</h3><div class="cast-grid">${visible.map(character=>{const relation=character.id==="azhe"?"主線人物":`關係 ${state.relations[character.id]??0}/100／Lv.${state.characterLevels?.[character.id]||1}`;return `<figure><img src="${character.src}" alt="${esc(character.alt)}" loading="lazy" decoding="async"><figcaption><b>${character.name}</b><span>${character.role}</span><small>${relation}</small></figcaption></figure>`;}).join("")}</div></section>`;}
function territoryLine(){const owned=controlledTerritories(state),income=territoryIncome(state),pending=state.pendingRetaliation?territoryById(state.pendingRetaliation.territoryId):null,active=activeTeamMembers(state),passives=contactBonuses(state);return `<section class="overview-card ${pending?"danger-card":""}"><h3>城市勢力</h3><p>地盤 ${owned.length}/${TERRITORIES.length}　每日 +${income}　街頭成員 ${state.crew.members} 人　士氣 ${state.crew.morale}/100　支援戰力 ${crewPower(state)}</p><p>核心隊員 ${active.length}/${TEAM_LIMIT}：${active.map(member=>esc(member.name)).join("、")||"尚未編制"}</p><p class="muted">聯絡人常駐支援：${esc(bonusText(passives))||"尚無"}</p>${pending?`<strong class="danger">警告：${esc(pending.name)}遭到反攻，該處收入暫停。</strong>`:""}</section>`;}
function sideQuestLine(){if(!state.activeSideQuest)return `<section class="overview-card"><h3>進行中支線</h3><p class="muted">目前沒有進行中的支線任務。</p></section>`;const quest=SIDE_QUESTS.find(item=>item.id===state.activeSideQuest.id);return `<section class="overview-card"><h3>進行中支線</h3><div class="quest-line"><span>${esc(quest.title)}　節點 ${state.activeSideQuest.nodeIndex+1}/${quest.nodes.length}　風險 ${quest.risk}${state.activeSideQuest.deadlineDay?`　期限剩 ${Math.max(0,state.activeSideQuest.deadlineDay-state.day+1)} 天`:""}</span><button class="secondary" data-abandon>放棄</button></div></section>`;}
function buffLine(){return `<section class="overview-card"><h3>短期效果（${state.buffs?.length||0}）</h3>${state.buffs?.length?`<div class="buff-line">${state.buffs.map(buff=>`<span>${esc(buff.label)}：${ABILITY_LABELS[buff.ability]} +${buff.value}／剩 ${buff.remaining} 階段</span>`).join("")}</div>`:'<p class="muted">目前沒有短期效果。</p>'}</section>`;}
function bonusText(bonuses={}){const labels={attack:"射擊",brawl:"格鬥",hack:"科技",flee:"撤離",hp:"耐久",armor:"護甲",medical:"醫療減免",reward:"勝利報酬",income:"額外收入",weapon:"火力",securityReduction:"警方戒備增幅減免"};return Object.entries(bonuses).filter(([,value])=>value).map(([key,value])=>`${labels[key]||key} +${value}`).join("、");}
function assetList(){const rows=Object.entries(state.assets||{}).flatMap(([category,items])=>items.map(item=>{const effects=bonusText({...item.bonuses,...(item.armor?{armor:item.armor}:{}),...(item.combatPower?{weapon:item.combatPower}:{})});return `<span title="${esc(item.description||"")}"><b>${ASSET_CATEGORY_LABELS[category]||category}</b> ${esc(item.name)} +${item.level||0}${item.dailyIncome?`／每日 +${item.dailyIncome}`:""}${effects?`／${esc(effects)}`:""}</span>`;}));return rows.join("")||'<span class="muted">目前沒有資產</span>';}
function cards(){const intro=state.deckType==="morning"?"下一個主線會永久保留；你可以先生活、經營或探索，直到主動選取。官方十五個任務完成後，自訂主線才會依建立順序出現。":state.deckType==="life"?"從五張生活卡牌中選擇這個階段想在城市裡進行的行為。":"從五張夜生活卡牌中選擇今晚安排；選定後不能返回。";return `<section class="panel"><p class="muted">${intro}</p><div class="cards">${state.candidates.map((id,i)=>{const e=getEvent(id,state),poor=e.cost&&state.player.resource<e.cost,isMain=!!e.main;return `<button class="card ${isMain?"main-card":""}" data-card="${e.id}" ${poor?"disabled":""}><span class="tag">${isMain?`可進行主線／第 ${e.chapter||state.chapter} 章${e.storyPosition?`・${e.storyPosition}/3`:""}`:`0${i+1}／${esc(e.tag)}`}</span><strong>${esc(e.title)}</strong><span>${esc(e.summary)}</span>${isMain?'<small class="accent">永久保留，直到選取完成</small>':""}${poor?`<small class="danger">現金不足，還需要 ${e.cost-state.player.resource}</small>`:""}</button>`}).join("")}</div></section>`;}
function getActivity(id){if(state.activityKind==="leisure")return LEISURE_CARDS.find(x=>x.id===id);if(state.activityKind==="training")return TRAINING_CARDS.find(x=>x.id===id);if(state.activityKind==="social")return CONTACTS.find(x=>x.id===id)||TEAM_MEMBERS.find(x=>x.id===id);if(state.activityKind==="purchase")return getEvent("asset_market",state).choices.find(x=>x.id===id);if(state.activityKind==="night:property")return state.assets.properties.find(x=>x.id===id);if(state.activityKind==="night:contact")return CONTACTS.find(x=>x.id===id);if(state.activityKind==="night:industry"||state.activityKind==="night:industryRisk")return state.assets.industries.find(x=>x.id===id);if(state.activityKind==="night:industryContact"){const [assetId,contactId]=id.split("|");const asset=state.assets.industries.find(x=>x.id===assetId),contact=CONTACTS.find(x=>x.id===contactId);return {id,title:`${asset.name}／${contact.name}`,detail:"同時恢復精神、處理生意並提升人物關係。",effects:[]};}}
function meetingButton(id){const contact=CONTACTS.find(item=>item.id===id),member=TEAM_MEMBERS.find(item=>item.id===id),level=state.characterLevels?.[id]||1,chance=characterLevelChance(level),met=!!state.metContacts[`${state.day}:${id}`];let cost=0,detail=contact?.detail||member?.summary||"";if(id==="difei"||id==="chenglan")detail+=` 隨機活動最高花費現金 3。`;else if(contact)cost=(contact.effects||[]).filter(effect=>effect.type==="resource.add"&&effect.value<0).reduce((sum,effect)=>sum-effect.value,0);else if(member){cost=teamTrainingCost(state,id);detail=`專長交流花費現金 ${cost}；關係必定 +4。`;};const poor=cost>state.player.resource;return `<button class="choice meeting-choice" data-activity="${id}" ${met||poor?"disabled":""}><b>${esc(contact?.name||member?.name||id)}　Lv.${level}</b>${esc(detail)}<div class="muted">本次專長突破率 ${chance}%；失敗仍會增加關係。</div>${met?'<div class="accent">今天已見過面</div>':poor?`<div class="danger">現金不足，還需要 ${cost-state.player.resource}</div>`:""}</button>`;}
function socialActivityView(title){const story=pendingCharacterEvent(state),contacts=state.activityOptions.filter(id=>state.knownContacts?.includes(id)),cores=state.activityOptions.filter(id=>state.team.roster.some(item=>item.id===id));return `<section class="panel meeting-panel"><div class="tag">${esc(title)}</div><h2>與人見面</h2><p class="muted">所有已認識或已招募的人物都會保留在清單。見面一定提升關係，角色等級越高則突破率越低；等級沒有上限。</p>${story?`<article class="character-story-callout"><div><span class="tag accent">永久人物事件／關係 ${story.threshold}</span><h3>${esc(story.title)}</h3><p>${esc(story.summary)}</p></div><button class="primary" data-character-event="${story.id}">進行事件</button></article>`:""}<details class="meeting-group" open><summary><b>劇情人物</b><span>${contacts.length} 人／點擊收合</span></summary><div class="choices">${contacts.map(meetingButton).join("")}</div></details><details class="meeting-group"><summary><b>核心隊員</b><span>${cores.length} 人／點擊展開</span></summary><div class="choices">${cores.map(meetingButton).join("")}</div></details><div class="choices"><button class="choice" data-activity="cancel"><b>取消安排</b>不進行活動，但仍消耗這個生活階段。</button></div></section>`;}
function activityView(){if(state.activityKind==="purchase")return purchaseView();const title=getEvent(state.selected,state).title,isNight=state.activityKind?.startsWith("night:");if(state.activityKind==="social")return socialActivityView(title);return `<section class="panel"><div class="tag">${esc(title)}</div><h2>${esc(title)}</h2><div class="choices">${state.activityOptions.map(id=>{const x=getActivity(id),poor=x.cost&&state.player.resource<x.cost;return `<button class="choice" ${isNight?"data-night-activity":"data-activity"}="${id}" ${poor?"disabled":""}><b>${esc(x.title||x.text||x.name)}</b>${esc(x.detail||`目前等級 +${x.level||0}`)}${poor?`<div class="danger">現金不足，還需要 ${x.cost-state.player.resource}</div>`:""}</button>`}).join("")}<button class="choice" ${isNight?"data-night-activity":"data-activity"}="cancel"><b>取消安排</b>不進行活動，但仍消耗這個${isNight?"晚上":"生活階段"}。</button></div></section>`;}
function purchaseButton(choice){const asset=choice.effects.find(effect=>effect.type==="asset.grant"),owned=asset&&state.assets[asset.category].some(item=>item.id===asset.assetId),poor=choice.cost&&state.player.resource<choice.cost;return `<button class="choice" data-activity="${choice.id}" ${owned||poor?"disabled":""}><b>${esc(choice.text)}</b>${esc(choice.detail)}${owned?'<div class="danger">已持有，可在「升級持有資產」強化</div>':poor?`<div class="danger">現金不足，還需要 ${choice.cost-state.player.resource}</div>`:""}</button>`;}
function purchaseView(){const event=getEvent("asset_market",state),choices=state.activityOptions.map(id=>event.choices.find(choice=>choice.id===id)).filter(Boolean),groups={};for(const choice of choices){const asset=choice.effects.find(effect=>effect.type==="asset.grant");if(asset)(groups[asset.category]??=[]).push(choice);}const order=["weapons","items","vehicles","properties","industries","luxuries"];return `<section class="panel market"><div class="tag">城市市場／分類購買</div><h2>${esc(event.title)}</h2><p class="muted">展開一個分類查看商品。卡牌會先列出現金、火力、耐久、撤離、報酬或每日收入等完整後果。</p>${order.filter(category=>groups[category]?.length).map(category=>`<details class="market-section"><summary><b>${ASSET_CATEGORY_LABELS[category]}</b><span>${groups[category].length} 項／點擊展開</span></summary><div class="choices">${groups[category].map(purchaseButton).join("")}</div></details>`).join("")}<details class="market-section"><summary><b>升級持有資產</b><span>無等級上限／等級越高成功率越低</span></summary>${upgradeList()}</details><div class="choices market-exit"><button class="choice" data-activity="leave"><b>暫不購買</b>保留現金並離開市場；仍會消耗這個生活階段。</button></div></section>`;}
function upgradeList(){const assets=Object.entries(state.assets).flatMap(([category,items])=>items.map(asset=>({category,...asset})));if(!assets.length)return '<p class="muted market-empty">目前沒有可升級資產。</p>';return `<div class="upgrade-list">${assets.map(asset=>{const level=asset.level||0,cost=Math.max(1,Math.ceil((asset.basePrice||1)*.25*(level+1))),chance=level===0?100:level===1?90:level===2?80:Math.max(5,80-(level-2)*5);return `<button class="secondary" data-upgrade="${asset.category}:${asset.id}" ${state.player.resource<cost?"disabled":""}>${esc(asset.name)} +${level}／升級 ${cost}／成功率 ${chance}%</button>`}).join("")}</div>`;}
function teamBoard(recruitCost){
  const active=new Set(state.team.active),totals=teamBonuses(state),cards=TEAM_MEMBERS.map(member=>{const roster=state.team.roster.find(item=>item.id===member.id),level=state.characterLevels?.[member.id]||roster?.level||1,isActive=active.has(member.id),dateLocked=state.day<member.unlockDay,recruitPrice=teamRecruitCost(member.id),scale=1+Math.max(0,level-1)*.25,current=Object.fromEntries(Object.entries(member.bonuses).map(([key,value])=>[key,Math.round(value*scale)])),storyLocked=member.recruitable===false&&!roster,art=member.art||`assets/images/team/${member.id}.webp`;let action;if(roster)action=`<div class="team-actions"><button class="secondary" data-team-toggle="${member.id}">${isActive?"撤下出勤":"編入出勤"}</button></div>`;else if(storyLocked)action=`<button class="secondary" disabled>${member.storyUnlock==="chapter1"?"完成第一章後自動加入":"由人物故事加入"}</button>`;else action=`<button class="secondary" data-team-recruit="${member.id}" ${dateLocked||state.player.resource<recruitPrice?"disabled":""}>${dateLocked?`第 ${member.unlockDay} 日後聯絡`:state.player.resource<recruitPrice?`還缺現金 ${recruitPrice-state.player.resource}`:`招募${member.name}`}</button>`;return `<article class="team-card ${isActive?"active":""}"><div class="team-card-head"><img src="${art}" alt="${esc(`${member.name}，${member.role}`)}" loading="lazy" decoding="async"><div><div class="tag">${roster?`${isActive?"出勤中":"待命"}／Lv.${level}`:storyLocked?"劇情解鎖":dateLocked?`第 ${member.unlockDay} 日解鎖`:`可招募／現金 ${recruitPrice}`}</div><h3>${esc(member.name)} <small>${esc(member.role)}</small></h3></div></div><p>${esc(member.summary)}</p><div class="team-effects">${esc(bonusText(current))}</div>${action}</article>`;}).join("");return `<details class="board-section"><summary><b>核心行動團隊</b><span>出勤 ${active.size}/${TEAM_LIMIT}／已招募 ${state.team.roster.length}/${TEAM_MEMBERS.length}</span></summary><div class="team-summary"><b>目前專長總和</b><span>${esc(bonusText(totals))||"尚未有核心隊員出勤"}</span><small>只有出勤隊員提供專長；最多 ${TEAM_LIMIT} 人。角色升級統一透過「與人見面」，成功率隨等級下降。</small></div><div class="team-grid">${cards}</div></details><details class="board-section"><summary><b>街頭成員</b><span>${state.crew.members}/20 人／士氣 ${state.crew.morale}/100／支援戰力 ${crewPower(state)}</span></summary><div class="crew-panel"><div><b>擴充一般人手</b><span>一般成員提供基礎支援；核心隊員則提供射擊、格鬥、駭客、醫療與收益等專長。</span></div><button class="secondary" data-recruit ${state.crew.members>=20||state.player.resource<recruitCost?"disabled":""}>招募街頭成員／現金 ${recruitCost}</button></div></details>`;}
function factionBoard(){
  const pending=state.pendingRetaliation,owned=controlledTerritories(state),recruitCost=6+state.crew.members*3,tooInjured=state.player.health<20;
  const factionCards=FACTIONS.map(faction=>{const status=state.factions[faction.id],unlocked=state.day>=faction.unlockDay,cost=factionFightCost(faction.id),held=TERRITORIES.filter(territory=>state.territories[territory.id].owner===faction.id).length;return `<article class="faction-card" style="--faction:${faction.color}"><div class="tag">${unlocked?`勢力戰力 ${faction.strength}`:`第 ${faction.unlockDay} 日解鎖`}</div><h3>${esc(faction.name)}</h3><p>${esc(faction.style)}</p><div class="faction-stats"><span>敵意 <b>${status.hostility}/100</b></span><span>敬意 <b>${status.respect}/100</b></span><span>控制地盤 <b>${held}</b></span><span>戰績 <b>${status.wins}勝／${status.losses}敗</b></span></div><button class="secondary" data-faction-fight="${faction.id}" ${!unlocked||tooInjured||state.player.resource<cost?"disabled":""}>挑戰巡街隊${cost?`／情報費 ${cost}`:"／免費"}</button></article>`}).join("");
  const territoryCards=TERRITORIES.map(territory=>{const control=state.territories[territory.id],owner=control.owner==="player"?"你的勢力":factionById(control.owner)?.name||"無主地帶",unlocked=state.day>=territory.unlockDay,isOwned=control.owner==="player",isPending=pending?.territoryId===territory.id,level=control.level||0,income=territory.income+level*2,fortifyCost=territoryFortifyCost(state,territory.id),disabled=tooInjured||state.player.resource<territory.entryCost;let action;if(!unlocked)action=`<button disabled>第 ${territory.unlockDay} 日取得進攻情報</button>`;else if(isPending)action=`<button class="danger-button" data-territory-fight="${territory.id}" ${tooInjured?"disabled":""}>立即防守地盤／免費</button>`;else if(isOwned)action=`<button class="secondary" data-fortify="${territory.id}" ${state.player.resource<fortifyCost?"disabled":""}>強化地盤 +${level+1}／現金 ${fortifyCost}</button>`;else action=`<button class="primary" data-territory-fight="${territory.id}" ${disabled?"disabled":""}>進攻地盤／準備費 ${territory.entryCost}</button>`;return `<article class="territory-card ${isOwned?"owned":""} ${isPending?"attacked":""}"><img class="territory-art" src="assets/images/territories/${territory.id}.webp" alt="${esc(`${territory.name}，${territory.district}`)}" loading="lazy" decoding="async"><div class="tag">${esc(territory.district)}／${isOwned?`每日 +${income}`:`勝利現金 +${territory.reward}`}</div><h3>${esc(territory.name)} ${level?`<small>+${level}</small>`:""}</h3><p>${esc(territory.perk)}</p><div class="owner">目前控制：<b>${esc(owner)}</b>／敵方戰力 ${territory.enemyHp}</div>${action}</article>`}).join("");
  return `<section class="panel faction-board"><div class="tag accent">城市勢力／主動行動</div><h2>建構團隊、選擇對手或經營地盤</h2><p class="muted">核心隊員、街頭人手、幫派與地盤預設收合。編制核心隊員不消耗階段；招募或開戰會使用本階段，人物成長則在「與人見面」進行。</p>${pending?`<div class="retaliation"><b>${esc(territoryById(pending.territoryId).name)}遭到${esc(factionById(pending.factionId).name)}反攻</b><span>在完成防守前，這塊地盤暫停收入；若戰敗或撤離，地盤會失守。</span></div>`:""}${teamBoard(recruitCost)}<details class="board-section"><summary><b>城市幫派</b><span>${FACTIONS.length} 個勢力／點擊展開</span></summary><div class="faction-grid">${factionCards}</div></details><details class="board-section"><summary><b>城市地盤</b><span>控制 ${controlledTerritories(state).length}/${TERRITORIES.length}／點擊展開</span></summary><div class="territory-grid">${territoryCards}</div></details><div class="actions"><button class="secondary" data-back>返回五張卡</button></div></section>`;
}
function sideQuestPick(){return `<section class="panel"><div class="tag">支線任務牌堆／3選1</div><h2>選擇一項支線任務</h2><p class="muted">只公開可能影響與風險，不顯示精確結果。全部拒絕仍會消耗階段。</p><div class="cards sidequest-cards">${state.sideQuestCandidates.map(id=>{const q=SIDE_QUESTS.find(x=>x.id===id);return `<button class="card" data-quest="${id}"><span class="tag">${q.type}／風險 ${q.risk}</span><strong>${esc(q.title)}</strong><span>${esc(q.summary)}</span><small>可能影響：${q.possible.join("、")}${q.deadlineDays?`／期限 ${q.deadlineDays} 天`:""}</small></button>`}).join("")}</div><div class="actions"><button class="secondary" data-decline-quests>全部拒絕</button></div></section>`;}
function sideQuestNode(){const q=SIDE_QUESTS.find(x=>x.id===state.activeSideQuest.id),node=q.nodes[state.activeSideQuest.nodeIndex];return `<section class="panel"><div class="tag">${q.type}支線／風險 ${q.risk}</div><h2>${esc(node.title)}</h2><p>${esc(node.text)}</p><p class="muted">系統將從 ${q.abilities.map(k=>ABILITY_LABELS[k]).join("、")} 中自動使用最高能力。</p><div class="choices">${node.choices.map(c=>`<button class="choice" data-quest-choice="${c.id}"><b>${esc(c.text)}</b>結果會依能力檢定與任務隨機狀況改變。</button>`).join("")}</div></section>`;}
function eventView(){const e=getEvent(state.selected,state);return `<section class="panel event-panel">${responsiveArt(EVENT_ART[e.id],"event-art")}<div class="tag">${esc(e.tag)}</div><h2>${esc(e.title)}</h2><p>${esc(e.summary)}</p><div class="choices">${e.choices.map(c=>{const asset=c.effects.find(effect=>effect.type==="asset.grant");const owned=asset&&state.assets?.[asset.category]?.some(item=>item.id===asset.assetId);const poor=c.cost&&state.player.resource<c.cost;const unavailable=owned||poor;return `<button class="choice" data-choice="${c.id}" ${unavailable?"disabled":""}><b>${esc(c.text)}</b>${esc(c.detail)}${c.check?`<div class="muted">${ABILITY_LABELS[c.check.ability]}檢定／風險行動</div>`:""}${owned?'<div class="danger">已持有</div>':poor?`<div class="danger">現金不足，還需要 ${c.cost-state.player.resource}</div>`:""}</button>`}).join("")}</div><div class="actions"><button class="secondary" data-back>返回五張卡</button></div></section>`;}
function characterEventView(){const e=characterEventById(state.selectedCharacterEvent);return `<section class="panel event-panel character-event-panel">${responsiveArt(EVENT_ART[e.id],"event-art")}<div class="tag accent">${esc(e.tag)}／永久保留事件</div><h2>${esc(e.title)}</h2><p>${esc(e.summary)}</p><div class="choices">${e.choices.map(choice=>`<button class="choice" data-character-choice="${choice.id}"><b>${esc(choice.text)}</b>${esc(choice.detail)}</button>`).join("")}</div></section>`;}
function chapterTransitionView(){const transition=state.chapterTransition;return `<section class="panel chapter-transition"><div class="tag accent">${esc(transition.title)}</div><h2>第 ${transition.to} 章即將開始</h2><p>主線只記錄完成順序，不限制天數。下一個任務會在上午永久保留；你仍可先處理生活、人物、產業與城市勢力。</p>${transition.from===1?'<p class="accent">程嵐已透過內部管道與你取得聯繫，並加入聯絡人與核心隊員名單。</p>':""}<div class="actions"><button class="primary" data-chapter-continue>進入下一章</button></div></section>`;}
function result(){const r=state.lastResult;return `<section class="panel"><div class="tag">${r.success?"結果／成功":"結果／承受代價"}</div><h2>${esc(r.title)}</h2><h3>${esc(r.choice)}</h3><p>${esc(r.summary)}</p>${r.check?`<p class="muted">檢定：${ABILITY_LABELS[r.check.ability]} ${state.player.abilities[r.check.ability]} ＋ 擲骰 ${r.roll}</p>`:""}<div class="actions"><button class="primary" data-continue>繼續</button></div></section>`;}
function battle(){const b=state.battle,faction=b.factionId?factionById(b.factionId):null,territory=b.territoryId?territoryById(b.territoryId):null,mode={capture:"搶奪地盤",defend:"防守地盤",skirmish:"主動挑戰",event:"事件戰鬥"}[b.battleType]||"事件戰鬥",active=activeTeamMembers(state),team=teamBonuses(state),gear=assetBonuses(state);return `<section class="panel battle-panel"><div class="tag danger">${mode}／回合 ${b.turn}／勝利現金 ${b.reward}</div><h2>${esc(b.title)}</h2><p class="muted">敵人：${esc(b.enemy)}${faction?`／${esc(faction.name)}`:""}${territory?`／${esc(territory.district)}`:""}</p><div class="battle-support"><span>街頭成員 ${state.crew.members} 人</span><span>核心隊員 ${active.map(member=>esc(member.name)).join("、")||"無"}</span><span>支援戰力 ${crewPower(state)}</span></div><p class="battle-effects">隊員專長：${esc(bonusText(team))||"無"}　／　裝備與產業：${esc(bonusText(gear))||"無"}</p><div class="hud battle-hud">${meter("你的戰力",Math.max(0,b.playerHp),140)}${meter("敵方戰力",Math.max(0,b.enemyHp),160)}</div><p>${esc(b.message)}</p><div class="choices battle-choices"><button class="choice" data-battle="attack"><b>快速射擊</b>槍法、武器、槍手與偵察專長共同造成傷害</button><button class="choice" data-battle="brawl"><b>帶隊近身格鬥</b>體能、近戰裝備與打手專長共同造成傷害</button><button class="choice" data-battle="hack"><b>控制戰場設備</b>科技、加密裝備與駭客專長造成穩定傷害</button><button class="choice" data-battle="guard"><b>尋找掩護</b>本回合受到的傷害減半</button><button class="choice retreat" data-battle="flee"><b>主動撤離</b>駕駛、觀察、車輛、物品與車手專長決定成功率；防守戰撤離會失去地盤</button></div></section>`;}
function ending(){return `<section class="panel"><div class="tag accent">第五章完成／官方主線 15/15</div><h2>五路亡命之後</h2><p>${esc(endingText(state))}</p><p>你的路線：${state.player.abilities.hacking>=state.player.abilities.physique?"都市策士":"街頭悍將"}。狄菲關係 ${state.relations.difei}，街坊聲望 ${state.world.people}，權貴勢力 ${state.world.corporate}。你控制 ${controlledTerritories(state).length} 塊地盤，帶領 ${state.crew.members} 人的街頭隊伍。</p><p class="muted">結局不會結束遊戲。繼續後可無限進行生活、夜生活、人物成長、產業與地盤經營；自訂主線也會依建立順序出現。</p><div class="actions"><button class="primary" data-freeplay>繼續自由遊玩</button><button class="secondary" data-new>重新開始</button><button class="secondary" data-log>查看完整紀錄</button></div></section>`;}
function log(){return `<details class="panel log-panel"><summary><b>最近的世界變化</b><span>${state.log.length?`共 ${state.log.length} 筆，點擊查看`:"尚無紀錄"}</span></summary><div class="log">${state.log.slice(-8).reverse().map(x=>`<p>#${x.sequence} D${x.day} ${esc(x.target)}：${esc(x.before)} → ${esc(x.after)}</p>`).join("")||"<p>尚無紀錄</p>"}</div></details>`;}
const valueFields=()=>[
  ["health","健康",state.player.health],["fatigue","疲勞",state.player.fatigue],["stress","精神壓力",state.player.stress],["resource","現金",state.player.resource],["mira","若琳信任",state.relations.mira],["kael","小凱關係",state.relations.kael],["zero","老六關係",state.relations.zero],["difei","狄菲關係",state.relations.difei],["chenglan","程嵐關係",state.relations.chenglan],["people","街坊聲望",state.world.people],["security","警方戒備",state.world.security],["gangs","幫派勢力",state.world.gangs],["corporate","權貴勢力",state.world.corporate],["ai","媒體聲量",state.world.ai],["crew.members","隊伍人數",state.crew.members],["crew.morale","隊伍士氣",state.crew.morale],["day","遊戲日數",state.day],...Object.entries(ABILITY_LABELS).map(([key,label])=>[`ability.${key}`,label,state.player.abilities[key]])];
function modifierView(){const baseCards=[...LIFE_CARDS,...NIGHT_CARDS,...CHAPTER_EVENTS,...(state.customCards||[])];return `<section class="panel modifier"><div class="tag accent">離線遊戲修改器</div><h2>修改各項數值</h2><p class="muted">變更會立即寫入目前存檔。遊戲日數沒有上限，章節只依主線完成順序決定；其他數值會自動限制在合法範圍。</p><div class="modifier-values">${valueFields().map(([path,label,value])=>`<label>${esc(label)}<span><input type="number" data-value-path="${path}" value="${value}"><button class="secondary" data-apply-value="${path}">套用</button></span></label>`).join("")}</div><hr><h2>新增或修改卡牌</h2><p class="muted">選擇既有卡牌會將它改成直接結算型卡牌；選擇「新增卡牌」則建立可離線保存的自訂卡。自訂主線會在官方十五個任務後依建立順序出現。</p><form data-card-editor><label>編輯目標<select name="baseId"><option value="">新增卡牌</option>${baseCards.map(card=>`<option value="${card.id}">${esc(card.title)}（${esc(card.id)}）</option>`).join("")}</select></label><div class="form-grid"><label>牌堆<select name="deck"><option value="night">夜生活</option><option value="life">生活</option><option value="main">主線</option></select></label><label>標籤<input name="tag" value="自訂"></label><label>卡牌名稱<input required name="title"></label><label>現金消費<input name="cost" type="number" value="0" min="0"></label></div><label>卡牌說明<textarea name="summary" required></textarea></label><label>結果故事<textarea name="result"></textarea></label><h3>使用後數值變化</h3><div class="form-grid">${[["health","健康"],["fatigue","疲勞"],["stress","精神壓力"],["resource","現金（不含上方消費）"],["mira","若琳信任"],["people","街坊聲望"]].map(([name,label])=>`<label>${label}<input name="effect_${name}" type="number" value="0"></label>`).join("")}<label>提升能力<select name="ability"><option value="">無</option>${Object.entries(ABILITY_LABELS).map(([key,label])=>`<option value="${key}">${label}</option>`).join("")}</select></label><label>能力變化<input name="abilityValue" type="number" value="0"></label></div><div class="actions"><button class="primary" type="submit">儲存卡牌</button></div></form>${state.customCards?.length?`<h3>自訂卡牌</h3><div class="custom-list">${state.customCards.map(card=>`<span><b>${esc(card.title)}</b><button class="secondary" data-delete-card="${card.id}">刪除</button></span>`).join("")}</div>`:""}</section>`;}
function render(){if(!state){start();return;}const views={cards,event:eventView,activity:activityView,factionBoard,sidequestPick:sideQuestPick,sidequestNode:sideQuestNode,battle,result,ending,characterEvent:characterEventView,chapterTransition:chapterTransitionView};const view=modifierOpen?modifierView():(views[state.phase]||cards)();app.innerHTML=`<main class="shell">${header()}${error?`<p class="danger">${esc(error)}</p>`:""}${view}${!modifierOpen&&state.phase!=="battle"?log():""}</main>`;bind();}
function start(){const saved=localStorage.getItem(SAVE_KEY);app.innerHTML=`<main class="shell start-shell"><section class="panel start-hero">${responsiveArt(HERO_ART,"start-hero-art","eager")}<div class="start-hero-copy"><div class="tag">海港市／現代</div><h1>罪城：五路亡命</h1><p>三年前，一場運鈔車爆炸案讓你入獄，也讓搭檔阿哲葬身火海。今天，死人打來電話，說那筆消失的錢從未離開這座城市。</p><p class="muted">五章十五個依序進行、永久保留的主線任務，沒有日數上限。認識五名聯絡人、集結十名核心隊員並編制五人出勤團隊；經營九個幫派、十五塊地盤與可無限升級的資產，結局後仍可自由遊玩。全程自動離線存檔。</p><div class="actions"><button class="primary" data-start>開始第一章</button>${saved?`<button class="secondary" data-load>繼續遊戲</button>`:""}</div></div></section></main>`;bind();}
function bind(){
  if(!state&&!document.querySelector("[data-start-modifier]")){const button=document.createElement("button");button.className="secondary";button.dataset.startModifier="";button.textContent="開啟遊戲修改器";document.querySelector(".actions")?.append(button);button.addEventListener("click",()=>{state=generateCards(newGame("不公開",Date.now()>>>0));modifierOpen=true;persist();render();});}
  document.querySelector("[data-modifier]")?.addEventListener("click",()=>{modifierOpen=!modifierOpen;error="";render();});
  document.querySelector("[data-start]")?.addEventListener("click",()=>{const seed=(Date.now()>>>0);state=generateCards(newGame("不公開",seed));persist();render();});
  document.querySelector("[data-load]")?.addEventListener("click",()=>{try{state=validateSave(JSON.parse(localStorage.getItem(SAVE_KEY)));persist();render();}catch(e){error=e.message;localStorage.removeItem(SAVE_KEY);start();}});
  document.querySelectorAll("[data-card]").forEach(el=>el.addEventListener("click",()=>commit(()=>selectCard(state,el.dataset.card))));
  document.querySelector("[data-back]")?.addEventListener("click",()=>{state={...state,phase:"cards",selected:null};render();});
  document.querySelectorAll("[data-choice]").forEach(el=>el.addEventListener("click",()=>commit(()=>resolveChoice(state,el.dataset.choice))));
  document.querySelectorAll("[data-character-event]").forEach(el=>el.addEventListener("click",()=>commit(()=>startCharacterEvent(state,el.dataset.characterEvent))));
  document.querySelectorAll("[data-character-choice]").forEach(el=>el.addEventListener("click",()=>commit(()=>resolveCharacterEventChoice(state,el.dataset.characterChoice))));
  document.querySelectorAll("[data-activity]").forEach(el=>el.addEventListener("click",()=>commit(()=>resolveActivity(state,el.dataset.activity))));
  document.querySelectorAll("[data-night-activity]").forEach(el=>el.addEventListener("click",()=>commit(()=>resolveNightOption(state,el.dataset.nightActivity))));
  document.querySelectorAll("[data-upgrade]").forEach(el=>el.addEventListener("click",()=>{const [category,id]=el.dataset.upgrade.split(":");commit(()=>upgradeAsset(state,category,id));}));
  document.querySelectorAll("[data-faction-fight]").forEach(el=>el.addEventListener("click",()=>commit(()=>startFactionFight(state,el.dataset.factionFight))));
  document.querySelectorAll("[data-territory-fight]").forEach(el=>el.addEventListener("click",()=>commit(()=>startTerritoryFight(state,el.dataset.territoryFight))));
  document.querySelectorAll("[data-fortify]").forEach(el=>el.addEventListener("click",()=>commit(()=>fortifyTerritory(state,el.dataset.fortify))));
  document.querySelector("[data-recruit]")?.addEventListener("click",()=>commit(()=>recruitCrew(state)));
  document.querySelectorAll("[data-team-recruit]").forEach(el=>el.addEventListener("click",()=>commit(()=>recruitTeamMember(state,el.dataset.teamRecruit))));
  document.querySelectorAll("[data-team-toggle]").forEach(el=>el.addEventListener("click",()=>commit(()=>toggleTeamMember(state,el.dataset.teamToggle))));
  document.querySelectorAll("[data-quest]").forEach(el=>el.addEventListener("click",()=>commit(()=>acceptSideQuest(state,el.dataset.quest))));
  document.querySelector("[data-decline-quests]")?.addEventListener("click",()=>commit(()=>declineSideQuests(state)));
  document.querySelectorAll("[data-quest-choice]").forEach(el=>el.addEventListener("click",()=>commit(()=>resolveSideQuestChoice(state,el.dataset.questChoice))));
  document.querySelector("[data-abandon]")?.addEventListener("click",()=>commit(()=>abandonSideQuest(state)));
  document.querySelectorAll("[data-battle]").forEach(el=>el.addEventListener("click",()=>commit(()=>battleAction(state,el.dataset.battle))));
  document.querySelector("[data-continue]")?.addEventListener("click",()=>commit(()=>continueStage(state)));
  document.querySelector("[data-chapter-continue]")?.addEventListener("click",()=>commit(()=>continueChapterTransition(state)));
  document.querySelector("[data-freeplay]")?.addEventListener("click",()=>commit(()=>continueFreePlay(state)));
  document.querySelector("[data-new]")?.addEventListener("click",()=>{localStorage.removeItem(SAVE_KEY);state=null;start();});
  document.querySelector("[data-log]")?.addEventListener("click",()=>{const panel=document.querySelector(".log-panel");if(panel)panel.open=true;document.querySelector(".log")?.scrollIntoView({behavior:"smooth"});});
  document.querySelectorAll("[data-apply-value]").forEach(button=>button.addEventListener("click",()=>{const path=button.dataset.applyValue,input=document.querySelector(`[data-value-path="${path}"]`);commit(()=>modifyValue(state,path,input.value));}));
  const editor=document.querySelector("[data-card-editor]");
  editor?.elements.baseId?.addEventListener("change",event=>{if(!event.target.value){editor.reset();return;}const card=getEvent(event.target.value,state);editor.elements.title.value=card.title||"";editor.elements.summary.value=card.summary||"";editor.elements.result.value=card.result||"";editor.elements.tag.value=card.tag||"自訂";editor.elements.cost.value=card.cost||0;editor.elements.deck.value=card.deck||((card.main||card.stage===0)?"main":card.stage===1?"life":"night");for(const name of ["health","fatigue","stress","resource","mira","people"])editor.elements[`effect_${name}`].value=0;});
  editor?.addEventListener("submit",event=>{event.preventDefault();const form=new FormData(editor),effects=[],mapping={health:["stat.add","health"],fatigue:["stat.add","fatigue"],stress:["stat.add","stress"],resource:["resource.add",null],mira:["relation.add","mira"],people:["world.add","people"]};for(const [name,[type,key]] of Object.entries(mapping)){const value=Number(form.get(`effect_${name}`)||0);if(value)effects.push({type,...(key?{key}:{}),value});}const ability=form.get("ability"),abilityValue=Number(form.get("abilityValue")||0);if(ability&&abilityValue)effects.push({type:"ability.add",key:ability,value:abilityValue});commit(()=>saveCardDefinition(state,{baseId:form.get("baseId"),deck:form.get("deck"),tag:form.get("tag"),title:form.get("title"),summary:form.get("summary"),result:form.get("result"),cost:form.get("cost"),effects}));});
  document.querySelectorAll("[data-delete-card]").forEach(button=>button.addEventListener("click",()=>commit(()=>deleteCustomCard(state,button.dataset.deleteCard))));
}
window.addEventListener("error",()=>{error="畫面發生錯誤；你的上一個階段存檔仍然安全。";});
if(location.protocol!=="file:"&&"serviceWorker" in navigator) navigator.serviceWorker.register("./sw.js").catch(()=>{});
start();
