export const LIFE_CARDS = [
  {id:"life_leisure",stage:1,tag:"日常",title:"處理日常需求",summary:"抽取5張日常卡牌，選擇吃飯、短暫休息、基礎療傷、整理裝備或蒐集情報。",hub:"leisure",repeatable:true},
  {id:"life_training",stage:1,tag:"成長",title:"進行訓練",summary:"從8種訓練中自由選擇，支付各自的現金與狀態代價。",hub:"training",repeatable:true},
  {id:"life_social",stage:1,tag:"社交",title:"與人見面",summary:"聯絡目前認識的人物，發展關係並交換消息。",hub:"social",repeatable:true},
  {id:"life_purchase",stage:1,tag:"資產",title:"購買",summary:"查看分類市場，購買或升級房產、車輛、武器、戰術物品、奢侈品及產業。",hub:"purchase",repeatable:true},
  {id:"life_work",stage:1,tag:"收入",title:"賺錢",summary:"系統依你的最高合理能力安排工作並自動結算。",hub:"work",repeatable:true},
  {id:"life_sidequest",stage:1,tag:"支線",title:"進行支線任務",summary:"從3張支線任務選1張，或繼續目前進行中的支線。",hub:"sidequest",repeatable:true},
  {id:"life_conflict",stage:1,tag:"勢力",title:"尋找對手",summary:"招募並編制核心團隊，或主動挑戰幫派、搶奪與防守地盤。",hub:"factions",repeatable:true}
];

export const LEISURE_CARDS = [
  {id:"leisure_free_rest",title:"在安全角落小睡",cost:0,detail:"免費／疲勞 -8、精神壓力 -3；5階段內膽識 +1。",effects:[{type:"stat.add",key:"fatigue",value:-8},{type:"stat.add",key:"stress",value:-3},{type:"ability.add",key:"will",value:1},{type:"buff.add",id:"rested",label:"短暫休息",ability:"will",value:1,duration:5}],result:"你找到一個不會被驅趕的安靜角落。睡得不深，至少讓眼睛和神經得到片刻休息。"},
  {id:"leisure_street_food",title:"吃一份路邊熱食",cost:2,detail:"現金 2／健康 +3、疲勞 -6；5階段內體能 +1。",effects:[{type:"resource.add",value:-2},{type:"stat.add",key:"health",value:3},{type:"stat.add",key:"fatigue",value:-6},{type:"ability.add",key:"management",value:1},{type:"buff.add",id:"fed",label:"吃飽",ability:"physique",value:1,duration:5}],result:"熱食簡單而油膩，但胃裡有了東西，接下來幾個小時便不會因飢餓分心。"},
  {id:"leisure_nutrition",title:"吃一頓營養餐",cost:6,detail:"現金 6／健康 +7、疲勞 -8、壓力 -4；5階段內體能 +2。",effects:[{type:"resource.add",value:-6},{type:"stat.add",key:"health",value:7},{type:"stat.add",key:"fatigue",value:-8},{type:"stat.add",key:"stress",value:-4},{type:"ability.add",key:"management",value:1},{type:"buff.add",id:"fed",label:"營養充足",ability:"physique",value:2,duration:5}],result:"你完整吃完蛋白質、蔬菜和熱湯。傷口仍在，但身體終於有材料開始修復自己。"},
  {id:"leisure_coffee",title:"到咖啡館喝咖啡",cost:3,detail:"現金 3／疲勞 -5、壓力 -5；5階段內觀察 +2。",effects:[{type:"resource.add",value:-3},{type:"stat.add",key:"fatigue",value:-5},{type:"stat.add",key:"stress",value:-5},{type:"ability.add",key:"perception",value:1},{type:"buff.add",id:"alert",label:"咖啡因",ability:"perception",value:2,duration:5}],result:"咖啡讓世界重新變得銳利。你坐在窗邊，看見幾個平常可能忽略的細節。"},
  {id:"leisure_bar",title:"到酒吧喝一杯",cost:6,detail:"現金 6／壓力 -12、疲勞 +5、街坊 +1；5階段內口才 +2。",effects:[{type:"resource.add",value:-6},{type:"stat.add",key:"stress",value:-12},{type:"stat.add",key:"fatigue",value:5},{type:"world.add",key:"people",value:1},{type:"ability.add",key:"social",value:1},{type:"buff.add",id:"social_mood",label:"微醺健談",ability:"social",value:2,duration:5}],result:"你請吧台旁的人喝了一輪，也聽到幾則不能登上新聞的傳聞。心情輕鬆了，腳步卻沒那麼穩。"},
  {id:"leisure_movie",title:"看一場午夜電影",cost:5,detail:"現金 5／壓力 -10、疲勞 -3；5階段內膽識 +2。",effects:[{type:"resource.add",value:-5},{type:"stat.add",key:"stress",value:-10},{type:"stat.add",key:"fatigue",value:-3},{type:"ability.add",key:"will",value:1},{type:"buff.add",id:"rested",label:"轉換心情",ability:"will",value:2,duration:5}],result:"黑暗裡沒有人注意你。兩個小時內，銀幕上的麻煩取代了現實裡的麻煩。"},
  {id:"leisure_sleep",title:"租房睡個好覺",cost:8,detail:"現金 8／健康 +8、疲勞 -20、壓力 -10；5階段內體能 +2。",effects:[{type:"resource.add",value:-8},{type:"stat.add",key:"health",value:8},{type:"stat.add",key:"fatigue",value:-20},{type:"stat.add",key:"stress",value:-10},{type:"ability.add",key:"physique",value:1},{type:"buff.add",id:"rested_body",label:"充分睡眠",ability:"physique",value:2,duration:5}],result:"你鎖門、關機，連續睡了幾個小時。醒來時城市沒有變好，但你的身體準備好了。"},
  {id:"leisure_treatment",title:"前往診所療傷",cost:10,detail:"現金 10／健康 +18、壓力 -4；5階段內膽識 +1。",effects:[{type:"resource.add",value:-10},{type:"stat.add",key:"health",value:18},{type:"stat.add",key:"stress",value:-4},{type:"ability.add",key:"will",value:1},{type:"buff.add",id:"treated",label:"妥善包紮",ability:"will",value:1,duration:5}],result:"醫師沒有問傷口來源，只留下乾淨縫線與一張沒有名字的收據。"}
];

const DAILY_TEXT={
  leisure_free_rest:["找地方短暫午休","免費／疲勞 -8、精神壓力 -3；5階段內膽識 +1。","你關掉手機短暫補眠，讓身體撐過下午，真正的完整休息仍要等到晚上。"],
  leisure_street_food:["吃份簡單午餐","現金 2／健康 +3、疲勞 -6；5階段內體能 +1。","你快速吃完一份熱食，至少不會在下一次行動中因飢餓分心。"],
  leisure_nutrition:["吃頓正式午餐","現金 6／健康 +7、疲勞 -8、精神 -4；5階段內體能 +2。","你坐下來完整吃完一餐，讓傷口與體力都有恢復的材料。"],
  leisure_coffee:["整理當日情報","現金 3／疲勞 -5、精神 -5；5階段內觀察 +2。","你在安靜角落整理照片、車牌和時間線，混亂的線索終於排出順序。"],
  leisure_bar:["聯絡城市中間人","現金 6／精神 -12、疲勞 +5、街坊 +1；5階段內口才 +2。","中間人收下聯絡費，替你確認幾條不能公開查詢的城市消息。"],
  leisure_movie:["檢查下一段行動路線","現金 5／精神 -10、疲勞 -3；5階段內膽識 +2。","你實際走過出口、死角與替代道路，知道出事時該往哪裡撤。"],
  leisure_sleep:["租用空間整理裝備","現金 8／健康 +8、疲勞 -20、精神 -10；5階段內體能 +2。","你租下不受打擾的工作空間，整理裝備並趁空檔補足短暫睡眠。"],
  leisure_treatment:["處理基礎傷勢","現金 10／健康 +18、精神 -4；5階段內膽識 +1。","你買齊藥品並重新包紮傷口，避免小傷在晚上變成大問題。"]
};
for(const card of LEISURE_CARDS){const text=DAILY_TEXT[card.id];if(text)[card.title,card.detail,card.result]=text;}

const training=(id,title,cost,ability,value,extra,detail,result)=>({id,title,cost,detail,effects:[{type:"resource.add",value:-cost},{type:"ability.add",key:ability,value},...extra],result});
export const TRAINING_CARDS = [
  training("train_physique","訓練體能",2,"physique",3,[{type:"stat.add",key:"fatigue",value:12},{type:"stat.add",key:"health",value:2}],"現金 2／疲勞 +12、健康 +2、體能 +3。","負重與間歇跑榨乾了最後一點力氣，身體卻記住了新的極限。"),
  training("train_reflex","訓練槍法",5,"reflex",3,[{type:"stat.add",key:"fatigue",value:6},{type:"stat.add",key:"stress",value:-2}],"現金 5／疲勞 +6、壓力 -2、槍法 +3。","彈著逐漸集中，扣扳機時的呼吸也重新穩定。"),
  training("train_hacking","訓練科技",5,"hacking",3,[{type:"stat.add",key:"stress",value:5}],"現金 5／壓力 +5、科技 +3。","你在二手設備上拆解監控系統，直到能看懂每一條防護漏洞。"),
  training("train_engineering","訓練駕駛",4,"engineering",3,[{type:"stat.add",key:"fatigue",value:7}],"現金 4／疲勞 +7、駕駛 +3。","反覆練習後，車尾終於能貼著護欄滑過而不留下刮痕。"),
  training("train_social","訓練口才",6,"social",3,[{type:"stat.add",key:"stress",value:3},{type:"world.add",key:"people",value:1}],"現金 6／壓力 +3、街坊 +1、口才 +3。","你在陌生場合練習讓人放下戒心，也學會何時應該保持沉默。"),
  training("train_perception","訓練觀察",3,"perception",3,[{type:"stat.add",key:"fatigue",value:4}],"現金 3／疲勞 +4、觀察 +3。","你沿街記錄車牌、出口與人群節奏，城市開始呈現另一層結構。"),
  training("train_will","訓練膽識",2,"will",3,[{type:"stat.add",key:"stress",value:6}],"現金 2／壓力 +6、膽識 +3。","你反覆面對最壞的可能，直到恐懼不再替你做決定。"),
  training("train_management","訓練生意",7,"management",3,[{type:"stat.add",key:"stress",value:4}],"現金 7／壓力 +4、生意 +3。","你研究帳目、價格與談判案例，開始看出每筆交易真正的成本。")
];

export const CONTACTS = [
  {id:"mira",name:"若琳",detail:"修車、喝咖啡或談論彼此的未來。",effects:[{type:"relation.add",key:"mira",value:6},{type:"ability.add",key:"social",value:2},{type:"stat.add",key:"stress",value:-5},{type:"resource.add",value:-3}],result:"若琳沒有替你解決問題，但她讓你記得自己仍有可以回去的地方。"},
  {id:"kael",name:"小凱",detail:"談車、試跑，或聽他吹噓下一場比賽。",effects:[{type:"relation.add",key:"kael",value:6},{type:"ability.add",key:"engineering",value:2},{type:"stat.add",key:"fatigue",value:3},{type:"resource.add",value:-2}],result:"小凱帶你繞過兩條沒人知道的捷徑，也終於停止把你當成過時的老傢伙。"},
  {id:"zero",name:"老六",detail:"交換市場消息，了解警方、幫派與商品行情。",effects:[{type:"relation.add",key:"zero",value:5},{type:"ability.add",key:"management",value:2},{type:"world.add",key:"security",value:-1},{type:"stat.add",key:"stress",value:2},{type:"resource.add",value:-3}],result:"老六從不免費聊天。你付了酒錢，也帶走幾條足以省下更多錢的消息。"},
  {id:"difei",name:"狄菲",detail:"助理與護衛；每次見面會在對練、整理情報與吃飯之間隨機進行。",effects:[],result:"狄菲替你確認下一段行程，仍不忘用一句『老闆』挑釁你的決定。"},
  {id:"chenglan",name:"程嵐",detail:"警務情報員；每次見面會在情報交換、系統演練與巡邏車會面之間隨機進行。",effects:[],result:"程嵐用最短的句子交代風險，已經替你留下不只一條退路。"}
];

export const JOBS = [
  {id:"job_moving",title:"替倉庫搬運貨物",abilities:["physique","management"],difficulty:32,reward:8,effects:[{type:"stat.add",key:"fatigue",value:9},{type:"ability.add",key:"physique",value:1}],result:"你完成整批搬運，領到一筆乾淨工錢。"},
  {id:"job_driver",title:"替車行運送客車",abilities:["engineering","perception"],difficulty:34,reward:10,effects:[{type:"stat.add",key:"fatigue",value:6},{type:"ability.add",key:"engineering",value:1}],result:"車輛準時抵達，連保險桿都沒有多一道刮痕。"},
  {id:"job_security",title:"替夜店維持秩序",abilities:["social","will","physique"],difficulty:35,reward:11,effects:[{type:"stat.add",key:"stress",value:5},{type:"ability.add",key:"social",value:1}],result:"整晚只動手一次，其餘麻煩都被幾句話擋在門外。"},
  {id:"job_devices",title:"維修監視與網路設備",abilities:["hacking","perception"],difficulty:36,reward:12,effects:[{type:"stat.add",key:"stress",value:4},{type:"ability.add",key:"hacking",value:1}],result:"你修好故障設備，也悄悄記住這棟樓的監控死角。"},
  {id:"job_accounts",title:"整理店家的混亂帳目",abilities:["management","social"],difficulty:34,reward:10,effects:[{type:"stat.add",key:"stress",value:4},{type:"ability.add",key:"management",value:1}],result:"你找出幾筆重複支出，店主很樂意支付約定報酬。"}
];

const node=(title,text,choices)=>({title,text,choices});
const sqChoice=(id,text,effects,result,failure)=>({id,text,effects,result,failure});
export const SIDE_QUESTS = [
  {id:"sq_mira_debt",type:"人物",title:"若琳的舊債",summary:"有人拿著若琳父親留下的借據上門。",risk:"中",possible:["若琳信任","現金","口才"],abilities:["social","management","will"],nodes:[node("討債人上門","若琳堅稱那張借據是偽造的。",[sqChoice("talk","查驗借據並談判",[{type:"relation.add",key:"mira",value:5},{type:"ability.add",key:"social",value:1}],"你找出借據日期的矛盾，討債人答應帶你見真正的債主。","對方拒絕談判並砸壞店面，若琳仍決定追查到底。"),sqChoice("pay","先替若琳付一部分",[{type:"resource.add",value:-6},{type:"relation.add",key:"mira",value:8}],"若琳不喜歡欠你，但接受了爭取時間的辦法。","錢被拿走，討債人卻立刻改口要求更多。")]),node("真正的債主","線索指向替高萬城洗錢的地下放款人。",[sqChoice("expose","取得帳本並公開威脅",[{type:"relation.add",key:"mira",value:10},{type:"world.add",key:"people",value:4},{type:"resource.add",value:8}],"放款人撕掉借據。若琳保住修車廠，也不再把所有重擔獨自扛著。","帳本沒拿到，但街坊共同作證迫使放款人退讓。")])],randomEvents:["討債人帶來假警察","借據上的證人突然失蹤"]},
  {id:"sq_kael_race",type:"人物",title:"小凱的最後一場比賽",summary:"小凱想用一場地下賽車還清幫派欠款。",risk:"高",possible:["小凱關係","健康","現金","駕駛"],abilities:["engineering","reflex","perception"],deadlineDays:3,nodes:[node("準備賽車","小凱的車撐不過完整賽程。",[sqChoice("repair","協助修車與試跑",[{type:"resource.add",value:-5},{type:"relation.add",key:"kael",value:6},{type:"ability.add",key:"engineering",value:1}],"你們把報廢零件拼成一輛能跑完比賽的車。","引擎仍有異音，但小凱拒絕退出。")]),node("最後一圈","幫派車手在彎道故意把小凱逼向護欄。",[sqChoice("guide","透過無線電指揮路線",[{type:"relation.add",key:"kael",value:10},{type:"resource.add",value:14},{type:"world.add",key:"gangs",value:-3}],"小凱從內線穿過，以半個車身贏下比賽和自由。","小凱撞毀車輛卻活了下來；債務仍被街坊募款還清。")])],randomEvents:["警方突然封閉一條賽道","對手在油箱裡動了手腳"]},
  {id:"sq_zero_book",type:"人物",title:"老六失蹤的帳本",summary:"老六丟了一本足以讓他被滅口的交易紀錄。",risk:"中",possible:["老六關係","科技","警方戒備"],abilities:["hacking","perception","social"],nodes:[node("尋找買家","帳本已經在地下市場轉手。",[sqChoice("trace","追蹤交易訊息",[{type:"relation.add",key:"zero",value:4},{type:"ability.add",key:"hacking",value:1},{type:"world.add",key:"security",value:2}],"你鎖定下一次交易的地點。","追蹤被發現，但假消息仍把你引到交貨區。")]),node("拿回帳本","買家同時向警長與港口幫報價。",[sqChoice("swap","用假帳本掉包",[{type:"relation.add",key:"zero",value:9},{type:"resource.add",value:10},{type:"world.add",key:"security",value:-2}],"真帳本回到老六手裡，假帳本則讓兩方開始互相懷疑。","掉包失敗，老六只搶回部分資料，但仍欠你一條命。")])],randomEvents:["交易地點臨時更換","警長的線人認出了你"]},
  {id:"sq_armored_tip",type:"犯罪",title:"便利商店運鈔時間",summary:"一條低風險運鈔情報可能帶來快錢。",risk:"高",possible:["現金","警方戒備","健康"],abilities:["perception","engineering","reflex"],deadlineDays:2,nodes:[node("踩點","確認保全、攝影機與撤離路線。",[sqChoice("quiet","低調觀察完整輪班",[{type:"ability.add",key:"perception",value:1},{type:"stat.add",key:"fatigue",value:5}],"你找到只有九十秒的安全窗口。","保全注意到你，但錯誤窗口仍足以行動。")]),node("動手","運鈔員比預定時間早到。",[sqChoice("take","照計畫奪取現金箱",[{type:"resource.add",value:20},{type:"world.add",key:"security",value:7},{type:"stat.add",key:"stress",value:5}],"你在警報響起前離開，現金足以支付數天開銷。","箱子只拿到一半，警方卻記住了車型。")])],randomEvents:["巡邏車臨時停在店外","現金箱安裝了染色裝置"]},
  {id:"sq_delivery",type:"犯罪",title:"不能打開的後車廂",summary:"港口幫出高價要求你送一輛車。",risk:"中",possible:["現金","幫派","駕駛"],abilities:["engineering","will","perception"],nodes:[node("接車","後車廂傳來一次微弱撞擊聲。",[sqChoice("drive","不打開，直接送達",[{type:"resource.add",value:8},{type:"ability.add",key:"engineering",value:1},{type:"stat.add",key:"stress",value:5}],"你保持沉默，把車送到指定倉庫。","車輛故障延誤，但收貨人仍讓任務繼續。"),sqChoice("look","停車查看後車廂",[{type:"world.add",key:"people",value:3},{type:"ability.add",key:"will",value:1}],"裡面是一名被綁架的會計，他願意用帳戶密碼換自由。","你被跟蹤者發現，只能帶著會計逃亡。")]),node("交付或救人","港口幫已在倉庫等候。",[sqChoice("finish","完成自己的選擇",[{type:"resource.add",value:14},{type:"world.add",key:"gangs",value:3}],"你離開倉庫時拿到了報酬，也知道這件事不會真正結束。","交易失控，你仍帶走部分報酬並留下新的敵人。")])],randomEvents:["車輛被臨檢攔下","後車廂裡的人認識若琳"]},
  {id:"sq_blackmail",type:"犯罪",title:"議員的飯店錄影",summary:"飯店員工願意出售一段足以勒索議員的影片。",risk:"中",possible:["現金","口才","權貴勢力"],abilities:["social","hacking","management"],nodes:[node("購買影片","員工臨時提高價碼。",[sqChoice("deal","談判並驗證影片",[{type:"resource.add",value:-5},{type:"ability.add",key:"social",value:1}],"影片是真的，而且還拍到一名意外出現的警官。","你多付了錢，至少拿到可用副本。")]),node("利用把柄","議員願意付錢，也願意提供一個名字。",[sqChoice("cash","收下封口費",[{type:"resource.add",value:18},{type:"world.add",key:"corporate",value:3}],"錢準時進入空殼帳戶，議員則成了不可靠的盟友。","議員只付一半，但影片仍足以保護你。"),sqChoice("truth","交給記者",[{type:"world.add",key:"people",value:7},{type:"world.add",key:"corporate",value:-5}],"新聞引爆全城，權貴第一次被迫公開回答問題。","電視台撤下報導，但影片已在街坊間流傳。")])],randomEvents:["影片其實有第二個買家","飯店保全開始清查員工"]},
  {id:"sq_eviction",type:"城市",title:"阻止非法驅逐",summary:"老人被房東與假警察趕出住處。",risk:"低",possible:["街坊聲望","健康","口才"],abilities:["social","will","management"],nodes:[node("面對房東","房東拿出一份有問題的法院命令。",[sqChoice("challenge","查證命令並召集鄰居",[{type:"world.add",key:"people",value:5},{type:"ability.add",key:"social",value:1}],"鄰居堵住樓梯，真正的警察也確認命令無效。","房東暫時退讓，卻雇人準備下一步。")]),node("解決產權","房東背後的空殼公司屬於高萬城。",[sqChoice("record","公開產權資料",[{type:"world.add",key:"people",value:8},{type:"world.add",key:"corporate",value:-3},{type:"relation.add",key:"mira",value:3}],"驅逐案成為全城新聞，住戶暫時保住了家。","新聞熱度不高，但律師同意暫停程序。")])],randomEvents:["假警察試圖沒收手機","住戶中有人向房東通風報信"]},
  {id:"sq_missing_kid",type:"城市",title:"尋找失蹤的少年",summary:"街坊少年整夜未歸，警方拒絕受理。",risk:"中",possible:["街坊聲望","觀察","精神"],abilities:["perception","social","hacking"],deadlineDays:3,nodes:[node("追查行蹤","最後影像出現在港區公車站。",[sqChoice("search","調閱影像並詢問司機",[{type:"ability.add",key:"perception",value:1},{type:"world.add",key:"people",value:3},{type:"stat.add",key:"fatigue",value:5}],"你找到少年搭上的貨車車牌。","影像模糊，但一名攤販提供了方向。")]),node("港區倉庫","少年被迫替偷車集團望風。",[sqChoice("rescue","帶他離開並警告集團",[{type:"world.add",key:"people",value:9},{type:"world.add",key:"gangs",value:-3},{type:"stat.add",key:"health",value:-3}],"少年安全回家，街坊開始把你視為真正能解決事情的人。","你受了傷，但仍把少年從後門送走。")])],randomEvents:["少年故意留下錯誤線索","偷車集團提前轉移地點"]},
  {id:"sq_water",type:"城市",title:"被污染的街區用水",summary:"居民生病，市府卻聲稱檢測一切正常。",risk:"低",possible:["街坊聲望","科技","現金"],abilities:["hacking","management","perception"],nodes:[node("取得水樣","必須進入封鎖的抽水站。",[sqChoice("sample","避開保全採集證據",[{type:"ability.add",key:"hacking",value:1},{type:"world.add",key:"security",value:2}],"樣本證明污染來自高萬城的建築工地。","保全發現入侵，但你仍帶出不完整樣本。")]),node("迫使市府處理","市府願意私下賠償，條件是保持沉默。",[sqChoice("public","公開檢測結果",[{type:"world.add",key:"people",value:8},{type:"world.add",key:"corporate",value:-4}],"供水被迫停用整修，居民得到乾淨飲水。","市府否認責任，但民間募款買下臨時濾水設備。"),sqChoice("settle","接受賠償並購買濾水器",[{type:"resource.add",value:10},{type:"world.add",key:"people",value:4}],"你用部分賠償添購設備，居民安全了，真相則暫時被壓下。","賠償縮水，但仍足以處理最危險的管線。")])],randomEvents:["檢測員遭到收買","工地趁夜排放第二批廢水"]}
];
