const buy = (id,text,detail,cost,asset,effects=[],result="") => {
  const enriched=effects.some(effect=>effect.type==="ability.add")?effects:[...effects,{type:"ability.add",key:"management",value:1}];
  return {id,text,detail,cost,result,effects:[{type:"resource.add",value:-cost},{type:"asset.grant",...asset},...enriched]};
};

export const EXTRA_MARKET_CHOICES = [
  buy("armored_sedan","購買防彈行政轎車","現金 55／車輛護甲 +12、撤離 +2；升級會繼續強化護甲。",55,{category:"vehicles",assetId:"vehicle_armored_sedan",name:"玄武防彈轎車",armor:12,bonuses:{flee:2},description:"防彈車門與失壓續跑胎，適合高風險撤離。"},[{type:"ability.add",key:"engineering",value:3},{type:"world.add",key:"security",value:4}],"你換上乾淨車牌，把玄武停進安全屋。它不低調，但能讓一場伏擊變成撤離。"),
  buy("street_bike","購買街頭重機","現金 20／撤離 +7、戰場耐久 +1；適合單人追蹤與高速脫離。",20,{category:"vehicles",assetId:"vehicle_street_bike",name:"赤隼重機",armor:1,bonuses:{flee:7},description:"能穿過車陣和狹窄巷口的高扭力重機。"},[{type:"ability.add",key:"engineering",value:2},{type:"stat.add",key:"stress",value:-2}],"赤隼的引擎聲劃過跨海橋。從此封鎖線不再只有正面突破這一種答案。"),
  buy("downtown_loft","購買市中心閣樓","現金 68／房產提供戰場耐久 +4、醫療減免 +2。",68,{category:"properties",assetId:"property_downtown_loft",name:"鐘塔閣樓",bonuses:{hp:4,medical:2},description:"靠近商業區與醫療資源的隱密高層住所。"},[{type:"ability.add",key:"management",value:3},{type:"stat.add",key:"stress",value:-12}],"鐘塔閣樓成了團隊的乾淨據點。沒有街坊耳目，卻能最快取得醫療與商業情報。"),

  buy("smg","購買緊湊型衝鋒槍","現金 26／武器火力 8、射擊傷害 +2；適合近距離連續交火。",26,{category:"weapons",assetId:"weapon_compact_smg",name:"V9緊湊衝鋒槍",combatPower:8,bonuses:{attack:2},description:"短槍身與大容量彈匣，適合車內與巷戰。"},[{type:"ability.add",key:"reflex",value:2},{type:"world.add",key:"security",value:4}],"老六把V9藏在運動袋底層。它能快速壓制多人，也會讓警方把案件提升為重大火力事件。"),
  buy("rifle","購買模組化突擊步槍","現金 36／武器火力 12、射擊傷害 +3；正面戰鬥的主力武器。",36,{category:"weapons",assetId:"weapon_modular_rifle",name:"ARX模組化步槍",combatPower:12,bonuses:{attack:3},description:"可換瞄具與槍管的可靠主力步槍。"},[{type:"ability.add",key:"reflex",value:3},{type:"world.add",key:"security",value:7}],"你測試了ARX的槍機與歸零。下一次地盤戰，你的隊伍終於有能壓住街口的主力火力。"),
  buy("stun_baton","購買電擊伸縮棍","現金 16／武器火力 3、格鬥傷害 +5；警方戒備增加較少。",16,{category:"weapons",assetId:"weapon_stun_baton",name:"雷蛇電擊棍",combatPower:3,bonuses:{brawl:5},description:"能制服近身目標、又不必立刻製造槍聲。"},[{type:"ability.add",key:"physique",value:2},{type:"world.add",key:"security",value:1}],"電弧在棍端跳動。鋼牙說，最好的武器有時不是殺人，而是讓剩下的人立刻投降。"),
  buy("marksman","購買精準射手步槍","現金 46／武器火力 15、射擊 +5、勝利報酬 +2。",46,{category:"weapons",assetId:"weapon_marksman_rifle",name:"長眼精準步槍",combatPower:15,bonuses:{attack:5,reward:2},description:"在敵人進入有效射程前就改變戰局的精準武器。"},[{type:"ability.add",key:"perception",value:3},{type:"world.add",key:"security",value:8}],"長眼被拆成三段送進城。鷹眼重新組裝後，只說了一句：現在可以先決定誰不能走出戰場。"),
  buy("breach_shotgun","購買戰術破門霰彈槍","現金 30／武器火力 10、格鬥 +3、戰場耐久 +2。",30,{category:"weapons",assetId:"weapon_breach_shotgun",name:"M12破門霰彈槍",combatPower:10,bonuses:{brawl:3,hp:2},description:"用於室內突破、近距離壓制與破壞掩體。"},[{type:"ability.add",key:"physique",value:2},{type:"ability.add",key:"reflex",value:1},{type:"world.add",key:"security",value:5}],"M12的第一發破鎖，第二發才留給門後的人。你的隊伍開始有能力主動選擇交戰距離。"),

  buy("vest","購買模組化防彈背心","現金 22／物品提供戰場耐久 +14、醫療減免 +2。",22,{category:"items",assetId:"item_ballistic_vest",name:"模組化防彈背心",bonuses:{hp:14,medical:2},description:"可更換抗彈板與掛載急救、彈藥裝備。"},[{type:"stat.add",key:"stress",value:-2}],"你替自己與核心隊員量好背心尺寸。它不會讓子彈消失，但能把致命傷變成一筆醫療帳單。"),
  buy("trauma_kit","購買戰術急救箱","現金 18／物品提供戰場耐久 +5、戰敗醫療費減免 +7。",18,{category:"items",assetId:"item_trauma_kit",name:"戰術急救箱",bonuses:{hp:5,medical:7},description:"止血帶、胸封與快速凝血用品組成的野戰急救包。"},[{type:"ability.add",key:"will",value:1},{type:"stat.add",key:"health",value:4}],"白鴿重新整理急救箱，要求所有人學會止血。從現在起，撤離不再只靠運氣。"),
  buy("encrypted_phone","購買加密通訊組","現金 24／物品提供環境科技傷害 +4、撤離 +3。",24,{category:"items",assetId:"item_encrypted_comms",name:"幽線加密通訊組",bonuses:{hack:4,flee:3},description:"一次性金鑰、跳頻耳機與無痕通訊手機。"},[{type:"ability.add",key:"hacking",value:2},{type:"world.add",key:"security",value:-2}],"幽靈替每個人設定代號與一次性金鑰。警察仍聽得見雜訊，卻再也拼不出完整計畫。"),
  buy("night_vision","購買低光夜視鏡","現金 28／物品提供射擊 +3、撤離 +4。",28,{category:"items",assetId:"item_night_vision",name:"黑潮低光夜視鏡",bonuses:{attack:3,flee:4},description:"在無燈倉庫、碼頭與地下道保持視野優勢。"},[{type:"ability.add",key:"perception",value:3}],"城市熄燈後，黑潮讓你看見別人看不見的路、槍口和恐懼。"),
  buy("ammo_case","購買專用彈藥箱","現金 20／物品提供射擊傷害 +5、武器火力 +2。",20,{category:"items",assetId:"item_ammo_case",name:"灰箱專用彈藥",combatPower:2,bonuses:{attack:5},description:"依隊伍武器預先分裝的穿透彈與低焰彈藥。"},[{type:"ability.add",key:"management",value:1},{type:"world.add",key:"security",value:3}],"帳房把每一發彈藥都登記到人。火力不只是有槍，而是在需要時每把槍都有正確的彈。"),
  buy("forged_documents","購買整套偽造證件","現金 26／物品提供撤離 +7、勝利報酬 +3。",26,{category:"items",assetId:"item_forged_documents",name:"白港偽造證件組",bonuses:{flee:7,reward:3},description:"包含車牌、公司文件與多組乾淨身分。"},[{type:"ability.add",key:"social",value:2},{type:"world.add",key:"security",value:-4}],"律師檢查每一枚鋼印。從今天起，運貨、收款與離城都能換一個名字。"),

  buy("gym","收購地下格鬥館","現金 26／產業每日 +4；格鬥 +3、戰場耐久 +3。",26,{category:"industries",assetId:"industry_underground_gym",name:"鐵籠格鬥館",dailyIncome:4,bonuses:{brawl:3,hp:3},description:"白天健身、夜裡比賽，也替隊伍提供訓練場。"},[{type:"ability.add",key:"physique",value:3},{type:"world.add",key:"people",value:2}],"你保留擂台與教練，趕走抽成過頭的莊家。格鬥館開始賺錢，也開始替你篩選能打的人。"),
  buy("logistics","收購港灣物流公司","現金 42／產業每日 +8；撤離 +3、額外產業收入 +2。",42,{category:"industries",assetId:"industry_harbor_logistics",name:"港灣物流公司",dailyIncome:8,bonuses:{flee:3,income:2},description:"合法貨單掩護地下運輸，提供車隊與倉儲。"},[{type:"ability.add",key:"management",value:4},{type:"world.add",key:"security",value:2}],"你的貨車每天合法進出港區，夾層則替真正重要的貨物保留位置。"),
  buy("pawnshop","收購二十四小時當舖","現金 34／產業每日 +6；射擊 +2、勝利報酬 +3。",34,{category:"industries",assetId:"industry_night_pawnshop",name:"黑燈當舖",dailyIncome:6,bonuses:{attack:2,reward:3},description:"快速處理戰利品，也提供零件與地下買家。"},[{type:"ability.add",key:"social",value:2},{type:"world.add",key:"gangs",value:2}],"黑燈的櫃檯從不問東西從哪來，只問你想多快換成現金。"),
  buy("security_company","收購私人保全公司","現金 50／產業每日 +9；戰場耐久 +10、射擊 +2。",50,{category:"industries",assetId:"industry_security_company",name:"城盾保全公司",dailyIncome:9,bonuses:{hp:10,attack:2},description:"合法持械人員、監控器材與快速支援車隊。"},[{type:"ability.add",key:"management",value:3},{type:"world.add",key:"security",value:6}],"城盾的制服與執照讓武裝人員能光明正大站在你的門口。代價是警方也開始研究這家公司。"),
  buy("clinic","收購地下診所","現金 48／產業每日 +8；醫療費減免 +9、戰場耐久 +5。",48,{category:"industries",assetId:"industry_underground_clinic",name:"白港地下診所",dailyIncome:8,bonuses:{medical:9,hp:5},description:"不問姓名的手術室與可靠醫療供應鏈。"},[{type:"ability.add",key:"will",value:3},{type:"world.add",key:"people",value:4}],"白鴿接管診所，第一條規則是先救人、再談帳。街坊記住了這件事。"),
  buy("media_studio","收購城市自媒體工作室","現金 54／產業每日 +10；所有戰鬥勝利報酬 +8。",54,{category:"industries",assetId:"industry_media_studio",name:"真浪媒體工作室",dailyIncome:10,bonuses:{reward:8},description:"把街頭消息變成流量、輿論與願意付錢的情報。"},[{type:"ability.add",key:"social",value:4},{type:"world.add",key:"ai",value:7}],"真浪會剪掉你的臉，留下對手倒下的畫面。名聲開始替每一場勝利抬高價格。")
];

export const ASSET_CATEGORY_LABELS = {properties:"房產",vehicles:"車輛",weapons:"武器",items:"物品",luxuries:"奢侈品",industries:"產業"};
