const buff=(id,label,ability,value)=>({type:"buff.add",id,label,ability,value,duration:5});

export const NIGHT_CARDS = [
  {id:"night_shelter",kind:"recovery",tag:"免費住宿",title:"找個安全角落過夜",summary:"免費／疲勞 -14、精神 -4；膽識 +1（5階段）。",cost:0,effects:[{type:"stat.add",key:"fatigue",value:-14},{type:"stat.add",key:"stress",value:-4},buff("night_rest","勉強睡過一晚","will",1)],result:"你把門頂住、手機關靜音，在城市醒來前搶到幾小時睡眠。"},
  {id:"night_home",kind:"recovery",tag:"房產住宿",title:"回持有的房產睡覺",summary:"免費／選擇住處；房產等級會提高恢復並解鎖里程碑效果。",cost:0,hub:"property",requires:"property"},
  {id:"night_store_food",kind:"recovery",tag:"平價飲食",title:"吃便利商店宵夜",summary:"現金 2／健康 +3、疲勞 -5、精神 -3。",cost:2,effects:[{type:"resource.add",value:-2},{type:"stat.add",key:"health",value:3},{type:"stat.add",key:"fatigue",value:-5},{type:"stat.add",key:"stress",value:-3}],result:"熱食櫃只剩最後一份便當。你坐在窗邊吃完，看著巡邏車從雨裡經過。"},
  {id:"night_diner",kind:"recovery",tag:"正餐",title:"到深夜食堂吃飯",summary:"現金 6／健康 +7、疲勞 -9、精神 -6；體能 +2（5階段）。",cost:6,effects:[{type:"resource.add",value:-6},{type:"stat.add",key:"health",value:7},{type:"stat.add",key:"fatigue",value:-9},{type:"stat.add",key:"stress",value:-6},buff("night_fed","熱食暖胃","physique",2)],result:"老闆沒有問你袖口的血從哪裡來，只把熱湯推到面前。"},
  {id:"night_fine_dining",kind:"recovery",tag:"高級餐飲",title:"享用高級餐廳晚餐",summary:"現金 16／健康 +12、疲勞 -12、精神 -12；口才 +3（5階段）。",cost:16,unlockCash:35,effects:[{type:"resource.add",value:-16},{type:"stat.add",key:"health",value:12},{type:"stat.add",key:"fatigue",value:-12},{type:"stat.add",key:"stress",value:-12},buff("night_polished","體面談吐","social",3)],result:"餐具擦得發亮，沒有人提高音量。這裡的祕密都藏在禮貌裡。"},
  {id:"night_massage",kind:"recovery",tag:"放鬆",title:"去按摩館放鬆",summary:"現金 10／疲勞 -18、精神 -10；體能 +2（5階段）。",cost:10,effects:[{type:"resource.add",value:-10},{type:"stat.add",key:"fatigue",value:-18},{type:"stat.add",key:"stress",value:-10},buff("night_relaxed","肌肉放鬆","physique",2)],result:"緊繃的肩背終於鬆開。離開時，你第一次沒有反覆確認身後。"},
  {id:"night_clinic",kind:"recovery",tag:"醫療",title:"到地下診所療傷",summary:"現金 15／健康 +24、精神 -5；膽識 +2（5階段）。",cost:15,effects:[{type:"resource.add",value:-15},{type:"stat.add",key:"health",value:24},{type:"stat.add",key:"stress",value:-5},buff("night_treated","完整治療","will",2)],result:"醫師收現金、不留病歷。乾淨縫線讓你撐過下一場麻煩。"},
  {id:"night_hotel",kind:"recovery",tag:"住宿",title:"入住商務旅館",summary:"現金 9／健康 +6、疲勞 -22、精神 -8；觀察 +1（5階段）。",cost:9,effects:[{type:"resource.add",value:-9},{type:"stat.add",key:"health",value:6},{type:"stat.add",key:"fatigue",value:-22},{type:"stat.add",key:"stress",value:-8},buff("night_hotel_rest","無人打擾","perception",1)],result:"你用假名字登記，拉緊窗簾，一覺睡到清潔車經過走廊。"},

  {id:"night_movie",kind:"entertainment",tag:"娛樂",title:"看一場午夜電影",summary:"現金 5／疲勞 -3、精神 -12；膽識 +2（5階段）。",cost:5,effects:[{type:"resource.add",value:-5},{type:"stat.add",key:"fatigue",value:-3},{type:"stat.add",key:"stress",value:-12},buff("night_movie_mood","轉換心情","will",2)],result:"兩小時裡，銀幕上的麻煩代替了現實中的麻煩。"},
  {id:"night_ktv",kind:"entertainment",tag:"娛樂",title:"去KTV唱到打烊",summary:"現金 8／疲勞 +4、精神 -16；口才 +2（5階段）。",cost:8,effects:[{type:"resource.add",value:-8},{type:"stat.add",key:"fatigue",value:4},{type:"stat.add",key:"stress",value:-16},buff("night_voice","放開嗓子","social",2)],result:"隔音門關上後，你終於能用最大聲音把那些名字唱掉。"},
  {id:"night_bar",kind:"entertainment",tag:"酒吧",title:"到酒吧喝一杯",summary:"現金 7／疲勞 +5、精神 -15；口才 +3（5階段）。30%可能遇到插曲。",cost:7,random:true,effects:[{type:"resource.add",value:-7},{type:"stat.add",key:"fatigue",value:5},{type:"stat.add",key:"stress",value:-15},buff("night_tipsy","微醺健談","social",3)],result:"酒精沒有解決問題，但讓問題的聲音小了一會兒。"},
  {id:"night_club",kind:"entertainment",tag:"夜店",title:"去夜店跳舞",summary:"現金 12／疲勞 +8、精神 -20；口才 +3（5階段）。30%可能遇到插曲。",cost:12,unlockDay:3,random:true,effects:[{type:"resource.add",value:-12},{type:"stat.add",key:"fatigue",value:8},{type:"stat.add",key:"stress",value:-20},buff("night_club_energy","人群焦點","social",3)],result:"低音震得胸口發麻。今晚沒有人談昨天，也沒有人保證明天。"},
  {id:"night_drive",kind:"entertainment",tag:"兜風",title:"開車到海邊兜風",summary:"現金 4／疲勞 +2、精神 -13；駕駛 +2（5階段）。持有車輛會增強效果。",cost:4,effects:[{type:"resource.add",value:-4},{type:"stat.add",key:"fatigue",value:2},{type:"stat.add",key:"stress",value:-13},buff("night_road_focus","夜路手感","engineering",2)],result:"跨海公路只剩引擎聲。城市在後照鏡裡縮成一條發光的傷口。"},

  {id:"night_social_food",kind:"social",tag:"人物",title:"找人一起吃宵夜",summary:"現金 8／選擇已認識人物；恢復疲勞與精神並提升關係。",cost:8,hub:"contact"},
  {id:"night_social_drink",kind:"social",tag:"人物",title:"邀人到酒吧喝一杯",summary:"現金 10／選擇已認識人物；精神大幅下降，可能交換情報。",cost:10,hub:"contact"},
  {id:"night_social_drive",kind:"social",tag:"人物",title:"約人一起夜間兜風",summary:"現金 6／選擇已認識人物；提升關係與駕駛短期效果。",cost:6,hub:"contact"},
  {id:"night_social_errand",kind:"social",tag:"人物",title:"陪人處理一件私事",summary:"現金 4／選擇已認識人物；提升關係，但可能增加疲勞。",cost:4,hub:"contact"},

  {id:"night_gamble",kind:"risk",tag:"高風險",title:"到地下賭場試手氣",summary:"現金 10／自動使用生意、觀察或膽識最高值；可能獲利並降低精神。",cost:10,risk:true,abilities:["management","perception","will"],difficulty:40,reward:24,effects:[{type:"stat.add",key:"fatigue",value:5},{type:"stat.add",key:"stress",value:-16}],failure:[{type:"resource.add",value:-8},{type:"stat.add",key:"fatigue",value:8},{type:"stat.add",key:"stress",value:5}]},
  {id:"night_race",kind:"risk",tag:"高風險",title:"參加非法街頭賽車",summary:"現金 8／自動使用駕駛、觀察或膽識最高值；可能贏得獎金，失敗可能受傷。",cost:8,risk:true,abilities:["engineering","perception","will"],difficulty:43,reward:28,effects:[{type:"stat.add",key:"fatigue",value:10},{type:"stat.add",key:"stress",value:-18}],failure:[{type:"stat.add",key:"health",value:-15},{type:"stat.add",key:"fatigue",value:14},{type:"world.add",key:"security",value:4}]},
  {id:"night_fight",kind:"risk",tag:"高風險",title:"到地下拳館下注或上場",summary:"現金 7／自動使用體能、槍法或膽識最高值；可能獲利並永久成長。",cost:7,risk:true,abilities:["physique","reflex","will"],difficulty:44,reward:25,effects:[{type:"stat.add",key:"fatigue",value:12},{type:"stat.add",key:"stress",value:-14},{type:"ability.add",key:"physique",value:1}],failure:[{type:"stat.add",key:"health",value:-18},{type:"stat.add",key:"fatigue",value:15},{type:"stat.add",key:"stress",value:4}]},
  {id:"night_private_party",kind:"risk",tag:"高風險",title:"接受私人派對邀請",summary:"現金 15／自動使用口才、生意或觀察最高值；可能取得情報、人脈與現金。",cost:15,unlockDay:5,risk:true,abilities:["social","management","perception"],difficulty:42,reward:26,effects:[{type:"stat.add",key:"fatigue",value:7},{type:"stat.add",key:"stress",value:-17},{type:"world.add",key:"corporate",value:2}],failure:[{type:"stat.add",key:"stress",value:8},{type:"world.add",key:"security",value:3},{type:"world.add",key:"corporate",value:-2}]},

  {id:"night_industry_patrol",kind:"industry",tag:"產業",title:"巡視自己的產業",summary:"免費／選擇持有產業；中等恢復並增加今晚收入。",cost:0,hub:"industry",requires:"industry"},
  {id:"night_industry_host",kind:"industry",tag:"產業",title:"在自家場所招待人物",summary:"現金 4／選擇產業與人物；同時恢復、經營並提升關係。",cost:4,hub:"industryContact",requires:"industry"},
  {id:"night_industry_problem",kind:"industry",tag:"產業",title:"處理打烊前的突發狀況",summary:"免費／選擇持有產業；自動以生意、口才或觀察檢定處理。",cost:0,hub:"industryRisk",requires:"industry"},

  {id:"combat_dock_brawl",kind:"combat",tag:"格鬥",title:"接受碼頭工人的擂台挑戰",summary:"免費／進入回合格鬥；勝利現金 +32、體能 +2，失敗仍可撤離。",cost:0,combat:true,unlockDay:3,enemy:"碼頭擂台冠軍",enemyHp:58,reward:32,rewardAbility:"physique",rewardAbilityValue:2,result:"你在貨櫃圍成的擂台站到最後，工人們把下注金與尊敬一起交給你。"},
  {id:"combat_debt_collectors",kind:"combat",tag:"街頭格鬥",title:"擊退堵門的地下討債人",summary:"現金 2／進入近身戰；勝利現金 +36、街坊 +4，失敗會受傷。",cost:2,combat:true,unlockDay:4,enemy:"持棍討債人",enemyHp:64,reward:36,rewardWorld:"people",rewardWorldValue:4,result:"最後一根球棒落地後，整條街的人都記住你替誰守住了門。"},
  {id:"combat_warehouse",kind:"combat",tag:"槍戰",title:"突襲藏有黑錢的港區倉庫",summary:"現金 4／進入槍戰；勝利現金 +42、槍法 +2，警方戒備可能提高。",cost:4,combat:true,unlockDay:6,enemy:"倉庫武裝守衛",enemyHp:72,reward:42,rewardAbility:"reflex",rewardAbilityValue:2,securityOnWin:3,result:"你踢開保險櫃，裡面的鈔票比情報說的更多；警笛也比預計來得更快。"},
  {id:"combat_convoy",kind:"combat",tag:"護送槍戰",title:"護送黑市醫師穿過封鎖區",summary:"現金 5／進入護送戰；勝利現金 +48、健康 +10，失敗仍能救出醫師。",cost:5,combat:true,unlockDay:8,enemy:"封鎖區攔截小隊",enemyHp:78,reward:48,rewardHealth:10,result:"醫師平安抵達安全屋，除了報酬，還替你處理了幾處一直沒時間照顧的舊傷。"},
  {id:"combat_hostage",kind:"combat",tag:"救援",title:"闖進汽車旅館救出被綁人質",summary:"現金 3／格鬥與槍戰；勝利現金 +44、街坊 +7、膽識 +1。",cost:3,combat:true,unlockDay:10,enemy:"旅館綁架集團",enemyHp:82,reward:44,rewardAbility:"will",rewardAbilityValue:1,rewardWorld:"people",rewardWorldValue:7,result:"人質從消防梯離開時，街坊已經替你封住警車最可能進來的路。"},
  {id:"combat_bounty",kind:"combat",tag:"懸賞槍戰",title:"追捕躲在夜市的懸賞槍手",summary:"現金 6／高難度槍戰；勝利現金 +55、觀察 +2，失敗會付出醫療費。",cost:6,combat:true,unlockDay:12,enemy:"被懸賞的職業槍手",enemyHp:90,reward:55,rewardAbility:"perception",rewardAbilityValue:2,result:"你在收攤的人潮裡逼他放下槍，兩個不同買家同時把賞金匯進你的空殼帳戶。"},
  {id:"combat_arena_final",kind:"combat",tag:"地下格鬥",title:"參加地下拳館冠軍賽",summary:"現金 8／高難度格鬥；勝利現金 +60、體能 +3、膽識 +2。",cost:8,combat:true,unlockDay:15,enemy:"地下拳館不敗冠軍",enemyHp:98,reward:60,rewardAbility:"physique",rewardAbilityValue:3,bonusWill:2,result:"冠軍倒在讀秒結束前。觀眾高喊的不是你的名字，而是你在街頭留下的綽號。"},
  {id:"combat_gang_vault",kind:"combat",tag:"大型槍戰",title:"攻下幫派藏金庫的廢棄酒店",summary:"現金 10／最高風險大型槍戰；勝利現金 +75、生意 +3、幫派勢力 -6。",cost:10,combat:true,unlockDay:18,enemy:"酒店金庫守衛隊",enemyHp:112,reward:75,rewardAbility:"management",rewardAbilityValue:3,rewardWorld:"gangs",rewardWorldValue:-6,result:"金庫門打開時，裡面是成捆現金、空白護照，以及足以讓另一個幫派開戰的帳冊。"}
];
