const buff=(id,label,ability,value)=>({type:"buff.add",id,label,ability,value,duration:5});

export const NIGHT_CARDS = [
  {id:"night_shelter",kind:"recovery",tag:"免費住宿",title:"找個安全角落過夜",summary:"免費／疲勞 -14、精神 -4；膽識 +1（5階段）。",cost:0,effects:[{type:"stat.add",key:"fatigue",value:-14},{type:"stat.add",key:"stress",value:-4},buff("night_rest","勉強睡過一晚","will",1)],result:"你把門頂住、手機關靜音，在城市醒來前搶到幾小時睡眠。"},
  {id:"night_home",kind:"recovery",tag:"房產住宿",title:"回持有的房產睡覺",summary:"免費／選擇住處；房產等級會提高恢復並解鎖里程碑效果。",cost:0,hub:"property",requires:"property"},
  {id:"night_store_food",kind:"recovery",tag:"平價飲食",title:"吃便利商店宵夜",summary:"現金 2／健康 +3、疲勞 -5、精神 -3。",cost:2,effects:[{type:"resource.add",value:-2},{type:"stat.add",key:"health",value:3},{type:"stat.add",key:"fatigue",value:-5},{type:"stat.add",key:"stress",value:-3}],result:"熱食櫃只剩最後一份便當。你坐在窗邊吃完，看著巡邏車從雨裡經過。"},
  {id:"night_diner",kind:"recovery",tag:"正餐",title:"到深夜食堂吃飯",summary:"現金 6／健康 +7、疲勞 -9、精神 -6；體能 +2（5階段）。",cost:6,effects:[{type:"resource.add",value:-6},{type:"stat.add",key:"health",value:7},{type:"stat.add",key:"fatigue",value:-9},{type:"stat.add",key:"stress",value:-6},buff("night_fed","熱食暖胃","physique",2)],result:"老闆沒有問你袖口的血從哪裡來，只把熱湯推到面前。"},
  {id:"night_fine_dining",kind:"recovery",tag:"高級餐飲",title:"享用高級餐廳晚餐",summary:"現金 16／健康 +12、疲勞 -12、精神 -12；口才 +3（5階段）。",cost:16,unlockCash:35,effects:[{type:"resource.add",value:-16},{type:"stat.add",key:"health",value:12},{type:"stat.add",key:"fatigue",value:-12},{type:"stat.add",key:"stress",value:-12},buff("night_polished","體面談吐","social",3)],result:"餐具擦得發亮，沒有人提高音量。這裡的祕密都藏在禮貌裡。"},
  {id:"night_massage",kind:"recovery",tag:"放鬆",title:"去按摩館放鬆",summary:"現金 10／疲勞 -18、精神 -10；體能 +2（5階段）。",cost:10,effects:[{type:"resource.add",value:-10},{type:"stat.add",key:"fatigue",value:-18},{type:"stat.add",key:"stress",value:-10},buff("night_relaxed","肌肉放鬆","physique",2)],result:"緊繃的肩背終於鬆開。離開時，你第一次沒有反覆確認身後。"},
  {id:"night_clinic",kind:"recovery",tag:"醫療",title:"到地下診所療傷",summary:"現金 15／健康 +24、精神 -5；膽識 +2（5階段）。",cost:15,effects:[{type:"resource.add",value:-15},{type:"stat.add",key:"health",value:24},{type:"stat.add",key:"stress",value:-5},buff("night_treated","完整治療","will",2)],result:"醫師收現金、不留病歷。乾淨縫線讓你撐過下一場麻煩。"},
  {id:"night_hotel",kind:"recovery",tag:"住宿",title:"入住商務旅館",summary:"現金 9／健康 +6、疲勞 -22、精神 -8；觀察 +1（5階段）。",cost:9,effects:[{type:"resource.add",value:-9},{type:"stat.add",key:"health",value:6},{type:"stat.add",key:"fatigue",value:-22},{type:"stat.add",key:"stress",value:-8},buff("night_hotel_rest","無人打擾","perception",1)],result:"你用假名字登記，拉緊窗簾，一覺睡到清潔車經過走廊。"},

  {id:"night_movie",kind:"entertainment",tag:"娛樂",title:"看一場午夜電影",summary:"現金 5／疲勞 -3、精神 -12；膽識 +2（5階段）。",cost:5,effects:[{type:"resource.add",value:-5},{type:"stat.add",key:"fatigue",value:-3},{type:"stat.add",key:"stress",value:-12},buff("night_movie_mood","轉換心情","will",2)],result:"兩小時裡，銀幕上的麻煩代替了現實中的麻煩。"},
  {id:"night_ktv",kind:"entertainment",tag:"娛樂",title:"去KTV唱到打烊",summary:"現金 8／疲勞 +4、精神 -16；口才 +2（5階段）。",cost:8,effects:[{type:"resource.add",value:-8},{type:"stat.add",key:"fatigue",value:4},{type:"stat.add",key:"stress",value:-16},buff("night_voice","放開嗓子","social",2)],result:"隔音門關上後，你終於能用最大聲音把那些名字唱掉。"},
  {id:"night_bar",kind:"entertainment",tag:"酒吧",title:"到酒吧喝一杯",summary:"現金 7／疲勞 +5、精神 -15；口才 +3（5階段）。30%可能遇到插曲。",cost:7,random:true,effects:[{type:"resource.add",value:-7},{type:"stat.add",key:"fatigue",value:5},{type:"stat.add",key:"stress",value:-15},buff("night_tipsy","微醺健談","social",3)],result:"酒精沒有解決問題，但讓問題的聲音小了一會兒。"},
  {id:"night_club",kind:"entertainment",tag:"夜店",title:"去夜店跳舞",summary:"現金 12／疲勞 +8、精神 -20；口才 +3（5階段）。30%可能遇到插曲。",cost:12,unlockDay:3,random:true,effects:[{type:"resource.add",value:-12},{type:"stat.add",key:"fatigue",value:8},{type:"stat.add",key:"stress",value:-20},buff("night_club_energy","人群焦點","social",3)],result:"低音震得胸口發麻。今晚沒有人談昨天，也沒有人保證明天。"},
  {id:"night_drive",kind:"entertainment",tag:"兜風",title:"開車到海邊兜風",summary:"現金 4／疲勞 +2、精神 -13；駕駛 +2（5階段）。持有車輛會增強效果。",cost:4,effects:[{type:"resource.add",value:-4},{type:"stat.add",key:"fatigue",value:2},{type:"stat.add",key:"stress",value:-13},buff("night_road_focus","夜路手感","engineering",2)],result:"跨海公路只剩引擎聲。城市在後照鏡裡縮成一條發光的傷口。"},

  {id:"night_social_food",kind:"social",tag:"人物",title:"找人一起吃宵夜",summary:"現金 8／選擇已認識人物；恢復疲勞與精神並提升關係。",cost:8,hub:"contact"},
  {id:"night_social_drink",kind:"social",tag:"人物",title:"邀人到酒吧喝一杯",summary:"現金 10／選擇已認識人物；精神大幅下降，可能交換情報。",cost:10,hub:"contact"},
  {id:"night_social_drive",kind:"social",tag:"人物",title:"約人一起夜間兜風",summary:"現金 6／選擇已認識人物；提升關係與駕駛短期效果。",cost:6,hub:"contact"},
  {id:"night_social_errand",kind:"social",tag:"人物",title:"陪人處理一件私事",summary:"現金 4／選擇已認識人物；提升關係，但可能增加疲勞。",cost:4,hub:"contact"},

  {id:"night_gamble",kind:"risk",tag:"高風險",title:"到地下賭場試手氣",summary:"現金 10／自動使用生意、觀察或膽識最高值；可能獲利並降低精神。",cost:10,risk:true,abilities:["management","perception","will"],difficulty:40,reward:24,effects:[{type:"stat.add",key:"fatigue",value:5},{type:"stat.add",key:"stress",value:-16}],failure:[{type:"resource.add",value:-8},{type:"stat.add",key:"fatigue",value:8},{type:"stat.add",key:"stress",value:5}]},
  {id:"night_race",kind:"risk",tag:"高風險",title:"參加非法街頭賽車",summary:"現金 8／自動使用駕駛、觀察或膽識最高值；可能贏得獎金，失敗可能受傷。",cost:8,risk:true,abilities:["engineering","perception","will"],difficulty:43,reward:28,effects:[{type:"stat.add",key:"fatigue",value:10},{type:"stat.add",key:"stress",value:-18}],failure:[{type:"stat.add",key:"health",value:-15},{type:"stat.add",key:"fatigue",value:14},{type:"world.add",key:"security",value:4}]},
  {id:"night_fight",kind:"risk",tag:"高風險",title:"到地下拳館下注或上場",summary:"現金 7／自動使用體能、槍法或膽識最高值；可能獲利並永久成長。",cost:7,risk:true,abilities:["physique","reflex","will"],difficulty:44,reward:25,effects:[{type:"stat.add",key:"fatigue",value:12},{type:"stat.add",key:"stress",value:-14},{type:"ability.add",key:"physique",value:1}],failure:[{type:"stat.add",key:"health",value:-18},{type:"stat.add",key:"fatigue",value:15},{type:"stat.add",key:"stress",value:4}]},
  {id:"night_private_party",kind:"risk",tag:"高風險",title:"接受私人派對邀請",summary:"現金 15／自動使用口才、生意或觀察最高值；可能取得情報、人脈與現金。",cost:15,unlockDay:5,risk:true,abilities:["social","management","perception"],difficulty:42,reward:26,effects:[{type:"stat.add",key:"fatigue",value:7},{type:"stat.add",key:"stress",value:-17},{type:"world.add",key:"corporate",value:2}],failure:[{type:"stat.add",key:"stress",value:8},{type:"world.add",key:"security",value:3},{type:"world.add",key:"corporate",value:-2}]},

  {id:"night_industry_patrol",kind:"industry",tag:"產業",title:"巡視自己的產業",summary:"免費／選擇持有產業；中等恢復並增加今晚收入。",cost:0,hub:"industry",requires:"industry"},
  {id:"night_industry_host",kind:"industry",tag:"產業",title:"在自家場所招待人物",summary:"現金 4／選擇產業與人物；同時恢復、經營並提升關係。",cost:4,hub:"industryContact",requires:"industry"},
  {id:"night_industry_problem",kind:"industry",tag:"產業",title:"處理打烊前的突發狀況",summary:"免費／選擇持有產業；自動以生意、口才或觀察檢定處理。",cost:0,hub:"industryRisk",requires:"industry"}
];
